# Daily Utility Snippets - 2026-05-24
# Generated by Gemini 1.5 Flash based on daily topics

from typing import Callable, Optional, TypeVar

# Define a TypeVar for generic numeric types (int or float)
T = TypeVar('T', int, float)


class UnionFind:
    """
    A Disjoint Set Union (DSU) data structure with path compression and union by rank.

    This data structure maintains a collection of disjoint sets and provides efficient
    operations for merging sets (union) and finding the representative (root)
    of the set to which an element belongs (find). It is 0-indexed.
    """

    def __init__(self, n: int):
        """
        Initializes the Union-Find structure for `n` elements.
        Each element is initially in its own set.

        Args:
            n: The number of elements (0-indexed) to manage.
        """
        if n < 0:
            raise ValueError("Number of elements must be non-negative.")
        self._parent = list(range(n))
        self._rank = [0] * n  # Used for union by rank heuristic
        self._num_components = n

    def find(self, i: int) -> int:
        """
        Finds the representative (root) of the set containing element `i`.
        Performs path compression to flatten the tree structure, making future
        find operations faster.

        Args:
            i: The element whose set representative is to be found.

        Returns:
            The representative (root) of the set containing `i`.
        
        Raises:
            IndexError: If the element index `i` is out of bounds.
        """
        if not (0 <= i < len(self._parent)):
            raise IndexError(f"Element index {i} out of bounds for {len(self._parent)} elements.")
        if self._parent[i] == i:
            return i
        # Path compression: set parent[i] directly to the root
        self._parent[i] = self.find(self._parent[i])
        return self._parent[i]

    def union(self, i: int, j: int) -> bool:
        """
        Unites the sets containing elements `i` and `j`.
        Uses union by rank heuristic to keep the tree flat, attaching the
        shorter tree under the root of the taller tree.

        Args:
            i: The first element.
            j: The second element.

        Returns:
            True if the sets were different and successfully merged, False otherwise
            (they were already in the same set).
        
        Raises:
            IndexError: If either element index `i` or `j` is out of bounds.
        """
        if not (0 <= i < len(self._parent)) or not (0 <= j < len(self._parent)):
            raise IndexError(f"Element indices ({i}, {j}) out of bounds for {len(self._parent)} elements.")

        root_i = self.find(i)
        root_j = self.find(j)

        if root_i != root_j:
            # Union by rank: attach smaller rank tree under root of larger rank tree
            if self._rank[root_i] < self._rank[root_j]:
                self._parent[root_i] = root_j
            elif self._rank[root_j] < self._rank[root_i]:
                self._parent[root_j] = root_i
            else:
                # Ranks are equal, choose one root and increment its rank
                self._parent[root_j] = root_i
                self._rank[root_i] += 1
            self._num_components -= 1
            return True
        return False

    def connected(self, i: int, j: int) -> bool:
        """
        Checks if two elements `i` and `j` belong to the same set (i.e., are connected).

        Args:
            i: The first element.
            j: The second element.

        Returns:
            True if `i` and `j` are in the same set, False otherwise.
        
        Raises:
            IndexError: If either element index `i` or `j` is out of bounds.
        """
        if not (0 <= i < len(self._parent)) or not (0 <= j < len(self._parent)):
            raise IndexError(f"Element indices ({i}, {j}) out of bounds for {len(self._parent)} elements.")
        return self.find(i) == self.find(j)

    def get_num_components(self) -> int:
        """
        Returns the current number of disjoint sets (connected components).

        Returns:
            The total number of distinct sets.
        """
        return self._num_components

# # Sample Use Case for UnionFind:
# # Initialize with 5 elements (0, 1, 2, 3, 4)
# uf = UnionFind(5)
# print(f"Initial components: {uf.get_num_components()}")  # Expected: 5

# # Union 0 and 1
# uf.union(0, 1)
# print(f"Are 0 and 1 connected? {uf.connected(0, 1)}")    # Expected: True
# print(f"Components after union(0,1): {uf.get_num_components()}") # Expected: 4

# # Union 2 and 3
# uf.union(2, 3)
# print(f"Are 1 and 3 connected? {uf.connected(1, 3)}")    # Expected: False
# print(f"Components after union(2,3): {uf.get_num_components()}") # Expected: 3

# # Union 0 and 3 (connects {0,1} with {2,3})
# uf.union(0, 3)
# print(f"Are 1 and 3 connected? {uf.connected(1, 3)}")    # Expected: True
# print(f"Components after union(0,3): {uf.get_num_components()}") # Expected: 2

# # Try to union elements already in the same set
# uf.union(1, 2)
# print(f"Components after union(1,2) (already connected): {uf.get_num_components()}") # Expected: 2

# # Example with element 4 remaining separate
# print(f"Are 0 and 4 connected? {uf.connected(0, 4)}")    # Expected: False
# print(f"Number of components: {uf.get_num_components()}")# Expected: 2 (set {0,1,2,3}, set {4})


def binary_search_predicate(
    low: T,
    high: T,
    predicate: Callable[[T], bool],
    find_min_true: bool = True,
    iterations: int = 100 # For float precision/safety; integer search loop is low <= high
) -> Optional[T]:
    """
    Performs a binary search on a range [low, high] to find a value that satisfies a predicate function.

    This function is useful when searching for a specific value 'x' where a boolean function
    `predicate(x)` changes its truth value monotonically.
    - If `find_min_true` is True: Searches for the minimum `x` for which `predicate(x)` is True.
      The predicate should follow a `F, F, F, T, T, T` pattern (monotonic non-decreasing).
    - If `find_min_true` is False: Searches for the maximum `x` for which `predicate(x)` is True.
      The predicate should follow a `T, T, T, F, F, F` pattern (monotonic non-increasing).

    Args:
        low: The lower bound of the search range (inclusive).
        high: The upper bound of the search range (inclusive).
        predicate: A callable that takes a value (T) and returns a boolean.
                   Its behavior should be monotonic as described above.
        find_min_true: If True (default), searches for the minimum `x` in the range
                       such that `predicate(x)` is True.
                       If False, searches for the maximum `x` in the range
                       such that `predicate(x)` is True.
        iterations: For floating point searches, this determines the number of refinements.
                    A value of 100-200 is typically sufficient for good precision.
                    For integer searches, this parameter is effectively ignored as the loop
                    terminates when `low > high`.

    Returns:
        The found value `x` if one exists in the range and satisfies the predicate.
        Returns None if no such value is found.
    """
    ans: Optional[T] = None
    
    is_integer_search = isinstance(low, int) and isinstance(high, int)

    if find_min_true: # Searching for the smallest 'x' where predicate(x) is True
        while (is_integer_search and low <= high) or (not is_integer_search and iterations > 0):
            mid: T
            if is_integer_search:
                mid = low + (high - low) // 2
            else:
                mid = low + (high - low) / 2
            
            if predicate(mid):
                ans = mid # mid is a potential candidate
                high = mid - (1 if is_integer_search else 0) # Try to find an even smaller 'mid'
            else:
                low = mid + (1 if is_integer_search else 0) # 'mid' is too small, look higher
            
            if not is_integer_search:
                iterations -= 1
        
        # After loop, if ans is not None, it's the smallest 'x' that satisfied predicate(x)
        # We perform an additional check with predicate(ans) to handle cases where
        # `ans` might have been set to an initial 'low' or 'high' for convenience,
        # but technically no valid 'x' was found within the actual search process
        # (e.g. if the entire range is False).
        return ans if ans is not None and predicate(ans) else None
    
    else: # find_max_true: Searching for the largest 'x' where predicate(x) is True
        while (is_integer_search and low <= high) or (not is_integer_search and iterations > 0):
            mid: T
            if is_integer_search:
                # For finding max, bias mid upwards to prevent infinite loops when `low`
                # might become `mid` and `high` doesn't change (e.g., [0,1], mid=0, P(0)=T, low=0)
                mid = low + (high - low + 1) // 2
            else:
                mid = low + (high - low) / 2
            
            if predicate(mid):
                ans = mid # mid is a potential candidate
                low = mid + (1 if is_integer_search else 0) # 'mid' is a candidate, try larger values
            else:
                high = mid - (1 if is_integer_search else 0) # 'mid' is too large, look lower
            
            if not is_integer_search:
                iterations -= 1
        
        # Similar validation for ans as in find_min_true
        return ans if ans is not None and predicate(ans) else None

# # Sample Use Case 1: Find minimum integer X such that X*X >= 25
# def is_sufficient_square(x: int) -> bool:
#     return x * x >= 25
# result_min_square = binary_search_predicate(0, 100, is_sufficient_square, find_min_true=True)
# print(f"Min X such that X*X >= 25: {result_min_square}")  # Expected: 5

# # Sample Use Case 2: Find maximum integer X such that X*X <= 24
# def is_valid_square(x: int) -> bool:
#     return x * x <= 24
# result_max_square = binary_search_predicate(0, 100, is_valid_square, find_min_true=False)
# print(f"Max X such that X*X <= 24: {result_max_square}")  # Expected: 4

# # Sample Use Case 3: Find minimum capacity (float) to load packages in M days
# # Problem: Ship `weights` in at most `D` days. Find minimum ship capacity.
# def can_ship(capacity: float, weights: list[int], D: int) -> bool:
#     days_needed = 1
#     current_load = 0.0
#     for w in weights:
#         if w > capacity: # Cannot ship a package larger than capacity
#             return False
#         if current_load + w <= capacity:
#             current_load += w
#         else:
#             days_needed += 1
#             current_load = w
#     return days_needed <= D

# package_weights = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# max_days = 5
# min_possible_capacity = float(max(package_weights)) # Smallest possible capacity is largest single package
# max_possible_capacity = float(sum(package_weights)) # Largest possible capacity is sum of all packages

# result_shipping = binary_search_predicate(
#     min_possible_capacity,
#     max_possible_capacity,
#     lambda cap: can_ship(cap, package_weights, max_days),
#     find_min_true=True,
#     iterations=100
# )
# print(f"Minimum shipping capacity for {max_days} days: {result_shipping:.2f}") # Expected: ~15.00 (e.g., 14.99 or 15.00)

# # Sample Use Case 4: No value satisfies (min_true case)
# def always_false(x: int) -> bool:
#     return False
# result_no_true = binary_search_predicate(1, 10, always_false, find_min_true=True)
# print(f"Result for always_false (min_true): {result_no_true}") # Expected: None

# # Sample Use Case 5: All values satisfy (max_true case)
# def always_true(x: int) -> bool:
#     return True
# result_all_true = binary_search_predicate(1, 10, always_true, find_min_true=False)
# print(f"Result for always_true (max_true): {result_all_true}") # Expected: 10

# # Sample Use Case 6: Find max X (float) such that X*X <= 24.0 (i.e., sqrt(24))
# def is_valid_square_float(x: float) -> bool:
#     return x * x <= 24.0
# result_max_square_float = binary_search_predicate(0.0, 10.0, is_valid_square_float, find_min_true=False, iterations=100)
# print(f"Max X (float) such that X*X <= 24.0: {result_max_square_float:.5f}") # Expected: ~4.89898 (which is sqrt(24))
# import math
# print(f"Actual sqrt(24): {math.sqrt(24):.5f}")
