# Daily Utility Snippets - 2026-07-05
# Generated by Gemini 1.5 Flash based on daily topics

import collections
from typing import List, Dict, Callable, Optional, TypeVar

# Type variable for generic numeric types used in binary search
T = TypeVar('T', int, float)


class PrimeUtils:
    """
    A utility class for prime number related operations,
    including generating primes using the Sieve of Eratosthenes
    and efficient prime factorization using precomputed smallest prime factors.
    """

    def __init__(self, n: int):
        """
        Initializes the PrimeUtils object by precomputing primes
        and smallest prime factors (SPF) up to n using a linear time Sieve.

        Args:
            n: The upper limit for prime precomputation (inclusive).
               All primes and smallest prime factors up to n will be computed.
               Must be a non-negative integer.
        """
        if n < 0:
            raise ValueError("n must be a non-negative integer.")
        self.n = n
        self.primes: List[int] = []
        self.spf: List[int] = [0] * (n + 1)  # spf[i] stores the smallest prime factor of i
        self._sieve()

    def _sieve(self) -> None:
        """
        Applies the Sieve of Eratosthenes to precompute primes and
        their smallest prime factors up to self.n.
        This is an optimized version that computes SPF in nearly linear time.
        """
        if self.n < 2:
            return

        # Initialize spf[i] as i (assuming i is prime until proven otherwise)
        for i in range(2, self.n + 1):
            self.spf[i] = i

        for i in range(2, self.n + 1):
            # If i is still its own smallest prime factor, it's prime
            if self.spf[i] == i:
                self.primes.append(i)

            # For each prime p in the list of found primes:
            # Mark multiples of p (i*p) with p as their smallest prime factor.
            # Optimization: only proceed if p <= spf[i] to ensure spf[i*p] is *smallest*
            # and to ensure each composite number is marked exactly once.
            for p in self.primes:
                if p > self.spf[i] or i * p > self.n:
                    break
                self.spf[i * p] = p

    def get_primes(self) -> List[int]:
        """
        Returns the list of prime numbers found up to self.n.

        Returns:
            A list of prime numbers in ascending order.
        """
        return self.primes

    def is_prime(self, num: int) -> bool:
        """
        Checks if a number is prime using the precomputed Sieve results.

        Args:
            num: The number to check for primality.

        Returns:
            True if num is prime, False otherwise.
        Raises:
            ValueError: If num is outside the precomputed range [0, self.n].
        """
        if not (0 <= num <= self.n):
            raise ValueError(f"Number {num} is outside the precomputed range [0, {self.n}]")
        if num < 2:
            return False
        return self.spf[num] == num

    def prime_factorize(self, num: int) -> Dict[int, int]:
        """
        Computes the prime factorization of a number using the precomputed SPF array.

        Args:
            num: The number to factorize.

        Returns:
            A dictionary where keys are prime factors and values are their exponents.
            Returns an empty dictionary for num < 2.
        Raises:
            ValueError: If num is outside the precomputed range [0, self.n].
        """
        if not (0 <= num <= self.n):
            raise ValueError(f"Number {num} is outside the precomputed range [0, {self.n}]")
        if num < 2:
            return {}

        factors: Dict[int, int] = collections.defaultdict(int)
        temp_num = num
        while temp_num > 1:
            factor = self.spf[temp_num]
            factors[factor] += 1
            temp_num //= factor
        return dict(factors)


def binary_search_first_true(
    low: T,
    high: T,
    condition: Callable[[T], bool],
    epsilon: Optional[float] = None
) -> Optional[T]:
    """
    Performs a binary search to find the smallest value `x` (integer or float)
    in the range `[low, high]` for which the `condition(x)` is True.
    The `condition` is assumed to be monotonically increasing:
    if `condition(x)` is True, then `condition(y)` is True for all `y >= x`.

    Args:
        low: The inclusive lower bound of the search range.
        high: The inclusive upper bound of the search range.
        condition: A callable that takes a value `x` and returns a boolean.
                   It should represent a monotonic property (False then True).
        epsilon: An optional float value for precision when searching for floats.
                 If provided, the search will continue for a fixed number of iterations
                 to achieve high precision. If not provided, it assumes integer search.

    Returns:
        The smallest value `x` in the range `[low, high]` for which `condition(x)` is True.
        Returns None if no such value exists (i.e., condition is never True within the range),
        or if the search space is invalid (e.g., low > high).

    Raises:
        ValueError: If `low` and `high` types are inconsistent with `epsilon` argument
                    (e.g., `epsilon` provided for integer bounds, or not provided for float bounds).

    Example Usage (Integer Search):
    # Find the smallest integer x in [0, 100] such that x*x >= 50
    # Expected output: 8 (since 7*7=49, 8*8=64)
    # result = binary_search_first_true(0, 100, lambda x: x * x >= 50)
    # print(f"Smallest x such that x*x >= 50 in [0,100]: {result}")

    Example Usage (Float Search):
    # Find the smallest float x in [0.0, 10.0] such that x*x >= 50.0
    # Expected output: ~7.07106781 (sqrt(50))
    # result = binary_search_first_true(0.0, 10.0, lambda x: x * x >= 50.0, epsilon=1e-7)
    # print(f"Smallest x such that x*x >= 50.0 in [0.0,10.0]: {result}")
    """
    if low > high:
        return None

    if epsilon is not None:
        if not (isinstance(low, float) and isinstance(high, float)):
            raise ValueError(
                "Epsilon provided, but low and/or high are not floats. "
                "Ensure float bounds when using epsilon."
            )
        
        # For float search, typically use a fixed number of iterations for precision.
        # 100-200 iterations are usually sufficient for standard float precision (e.g., 1e-7 to 1e-9)
        # over typical competitive programming ranges (e.g., 1e18).
        ans: Optional[T] = None
        for _ in range(100):
            mid = (low + high) / 2.0
            if condition(mid):
                ans = mid
                high = mid
            else:
                low = mid
        return ans
    else:
        # Integer search
        if not (isinstance(low, int) and isinstance(high, int)):
             raise ValueError(
                 "Epsilon not provided, but low and/or high are not integers. "
                 "Consider providing epsilon for float search."
            )

        ans: Optional[T] = None
        while low <= high:
            mid = low + (high - low) // 2  # Integer division, robust against overflow
            if condition(mid):
                ans = mid
                high = mid - 1
            else:
                low = mid + 1
        return ans
