# Daily Utility Snippets - 2026-05-26
# Generated by Gemini 1.5 Flash based on daily topics

from typing import Dict, List, Optional

class TrieNode:
    """A node in the Trie data structure."""
    def __init__(self):
        self.children: Dict[str, 'TrieNode'] = {}
        self.is_end_of_word: bool = False

class Trie:
    """
    A Trie (prefix tree) data structure for efficient string storage and retrieval.

    Supports insertion of words, checking for word existence, and checking for prefixes.
    This utility is extremely useful in problems involving dictionaries, autocomplete,
    spell checkers, and prefix-based string searching.
    It covers topics like Trie, String manipulation, and uses Hash Tables (dictionaries)
    internally for efficient child lookup.
    """

    def __init__(self):
        self.root = TrieNode()

    def insert(self, word: str) -> None:
        """
        Inserts a word into the Trie.

        Args:
            word: The string word to insert.
        """
        node = self.root
        for char in word:
            if char not in node.children:
                node.children[char] = TrieNode()
            node = node.children[char]
        node.is_end_of_word = True

    def _search_node(self, prefix: str) -> Optional[TrieNode]:
        """
        Helper method to traverse the Trie for a given prefix.

        Args:
            prefix: The prefix string to search for.

        Returns:
            The TrieNode corresponding to the end of the prefix if found,
            otherwise None.
        """
        node = self.root
        for char in prefix:
            if char not in node.children:
                return None
            node = node.children[char]
        return node

    def search_word(self, word: str) -> bool:
        """
        Checks if a complete word exists in the Trie.

        Args:
            word: The string word to search for.

        Returns:
            True if the word is found, False otherwise.
        """
        node = self._search_node(word)
        return node is not None and node.is_end_of_word

    def starts_with_prefix(self, prefix: str) -> bool:
        """
        Checks if there is any word in the Trie that starts with the given prefix.

        Args:
            prefix: The string prefix to check.

        Returns:
            True if any word starts with the prefix, False otherwise.
        """
        return self._search_node(prefix) is not None

# Sample Use Case for Trie:
# trie = Trie()
# trie.insert("apple")
# trie.insert("app")
# trie.insert("apricot")
#
# print(f"Search 'apple': {trie.search_word('apple')}")  # Expected: True
# print(f"Search 'appl': {trie.search_word('appl')}")    # Expected: False
# print(f"Starts with 'app': {trie.starts_with_prefix('app')}") # Expected: True
# print(f"Starts with 'bat': {trie.starts_with_prefix('bat')}") # Expected: False
# print(f"Search 'app': {trie.search_word('app')}")      # Expected: True


def sieve_of_eratosthenes(limit: int) -> List[bool]:
    """
    Generates a boolean list indicating primality for numbers up to a given limit
    using the Sieve of Eratosthenes algorithm.

    This is an extremely useful utility function in competitive programming and
    algorithmic problems involving number theory, prime factorization, and modular
    arithmetic. It efficiently precomputes primality for a range of numbers.
    It directly relates to Math and Array topics.

    The list `is_prime[i]` will be True if `i` is a prime number, False otherwise.
    The list is 0-indexed, so `is_prime[0]` and `is_prime[1]` will be False.

    Args:
        limit: An integer representing the upper bound (inclusive) for finding primes.
               Must be non-negative.

    Returns:
        A list of booleans where `is_prime[i]` is True if `i` is prime, False otherwise.

    Raises:
        ValueError: If limit is negative.
    """
    if limit < 0:
        raise ValueError("Limit must be a non-negative integer.")

    if limit < 2:
        return [False] * (limit + 1)

    is_prime: List[bool] = [True] * (limit + 1)
    is_prime[0] = False  # 0 is not prime
    is_prime[1] = False  # 1 is not prime

    # We only need to check factors up to sqrt(limit)
    # because if n = a * b, and a > sqrt(n), then b must be < sqrt(n).
    # So one of the factors will always be <= sqrt(n).
    p = 2
    while p * p <= limit:
        # If is_prime[p] is still True, then it is a prime
        if is_prime[p]:
            # Mark all multiples of p greater than or equal to p*p as not prime.
            # Multiples less than p*p would have already been marked by smaller primes.
            for multiple in range(p * p, limit + 1, p):
                is_prime[multiple] = False
        p += 1

    return is_prime

# Sample Use Case for Sieve of Eratosthenes:
# limit = 30
# is_prime_list = sieve_of_eratosthenes(limit)
#
# print(f"Primality up to {limit}:")
# for i, is_p in enumerate(is_prime_list):
#     if is_p:
#         print(f"{i} is prime")
#
# # Example: get a list of prime numbers themselves
# primes = [i for i, is_p in enumerate(is_prime_list) if is_p]
# print(f"\nPrimes up to {limit}: {primes}") # Expected: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
