# Daily Utility Snippets - 2026-05-23
# Generated by Gemini 1.5 Flash based on daily topics

from typing import List, Dict, TypeVar, Set, Optional

# Define a generic type for node identifiers, useful for type hinting in graph problems.
T = TypeVar('T')

def sieve_of_eratosthenes(limit: int) -> List[bool]:
    """
    Generates a boolean list indicating primality up to a given limit using the Sieve of Eratosthenes.

    The Sieve of Eratosthenes is an efficient algorithm for finding all prime numbers
    up to any given limit. It does so by iteratively marking as composite
    (i.e., not prime) the multiples of each prime, starting with the first prime number, 2.

    Args:
        limit: The upper bound (inclusive) for finding prime numbers.
               Must be a non-negative integer. If limit < 2, no primes are found
               in the typical sense (0 and 1 are not prime).

    Returns:
        A list of booleans, where `is_prime[i]` is True if `i` is a prime number,
        and False otherwise. The list has `limit + 1` elements.

    Raises:
        ValueError: If limit is negative.

    # Sample Usage:
    # is_prime_list = sieve_of_eratosthenes(30)
    # print(f"Primes up to 30: {[i for i, is_p in enumerate(is_prime_list) if is_p and i >= 2]}")
    # # Expected Output: Primes up to 30: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
    # print(f"Is 23 prime? {is_prime_list[23]}")
    # # Expected Output: Is 23 prime? True
    # print(f"Is 25 prime? {is_prime_list[25]}")
    # # Expected Output: Is 25 prime? False
    """
    if limit < 0:
        raise ValueError("Limit must be a non-negative integer for the Sieve of Eratosthenes.")

    is_prime = [True] * (limit + 1)
    if limit >= 0:
        is_prime[0] = False  # 0 is not prime
    if limit >= 1:
        is_prime[1] = False  # 1 is not prime

    p = 2
    while p * p <= limit:
        if is_prime[p]:
            # Mark all multiples of p greater than or equal to p*p as not prime.
            # Multiples less than p*p would have already been marked by smaller primes.
            for multiple in range(p * p, limit + 1, p):
                is_prime[multiple] = False
        p += 1
    return is_prime


def topological_sort(graph: Dict[T, List[T]]) -> Optional[List[T]]:
    """
    Performs a topological sort on a directed acyclic graph (DAG) using Depth-First Search (DFS).

    A topological sort is a linear ordering of vertices such that for every directed edge
    u -> v, vertex u comes before v in the ordering. It is only possible for DAGs.
    If the graph contains a cycle, a topological sort is not possible, and None is returned.

    Args:
        graph: An adjacency list representation of the graph.
               Keys are nodes (of type T), and values are lists of nodes reachable from
               the key node (its direct successors).
               Nodes can be any hashable type (e.g., int, str, tuple).
               Assumes nodes not present as keys have no outgoing edges.

    Returns:
        A list of nodes in topological order, or None if the graph contains a cycle.

    # Sample Usage 1 (Simple DAG):
    # graph1 = {
    #     'A': ['C', 'D'],
    #     'B': ['D', 'E'],
    #     'C': ['F'],
    #     'D': ['F', 'G'],
    #     'E': ['G'],
    #     'F': [],
    #     'G': []
    # }
    # print(f"Topological sort of graph1: {topological_sort(graph1)}")
    # # Expected Output: A valid topological order, e.g., ['B', 'E', 'A', 'C', 'D', 'G', 'F']
    # # (The exact order can vary for nodes with no strict dependency order)

    # Sample Usage 2 (Numeric Nodes):
    # graph2 = {
    #     0: [1, 2],
    #     1: [3],
    #     2: [3],
    #     3: []
    # }
    # print(f"Topological sort of graph2: {topological_sort(graph2)}")
    # # Expected Output: A valid topological order, e.g., [0, 2, 1, 3] or [0, 1, 2, 3]

    # Sample Usage 3 (Graph with a cycle):
    # cyclic_graph = {
    #     'A': ['B'],
    #     'B': ['C'],
    #     'C': ['A']
    # }
    # print(f"Topological sort of cyclic_graph: {topological_sort(cyclic_graph)}")
    # # Expected Output: None
    """
    # `visited` tracks nodes whose DFS traversal is entirely complete (including all descendants).
    visited: Set[T] = set()
    # `recursion_stack` tracks nodes currently in the active DFS recursion path.
    # Used to detect cycles (a back-edge to a node in this set indicates a cycle).
    recursion_stack: Set[T] = set()
    # `result` stores nodes in reverse topological order as they finish their DFS.
    result: List[T] = []

    def dfs(node: T) -> bool:
        """
        Helper function for DFS traversal, cycle detection, and building the topological order.
        Returns True if a cycle is detected during the traversal starting from 'node', False otherwise.
        """
        visited.add(node)
        recursion_stack.add(node)

        # Explore neighbors
        for neighbor in graph.get(node, []): # Use .get() to gracefully handle nodes not explicitly in graph.keys()
            if neighbor not in visited:
                # If neighbor not visited, recurse. If a cycle is found deeper, propagate it.
                if dfs(neighbor):
                    return True
            elif neighbor in recursion_stack:
                # If neighbor is in the current recursion stack, a back-edge is found, hence a cycle.
                return True

        # DFS for this node and all its descendants is complete.
        # Remove from recursion stack and add to result list.
        recursion_stack.remove(node)
        result.append(node)  # Add node to result (it will be reversed later for correct order)
        return False

    # Collect all unique nodes from the graph (both as keys and values) to ensure all
    # components and isolated nodes are considered, even those without outgoing edges.
    all_nodes: Set[T] = set(graph.keys())
    for neighbors_list in graph.values():
        all_nodes.update(neighbors_list)

    # Iterate through all nodes. If a node hasn't been visited, start a new DFS traversal.
    for node in all_nodes:
        if node not in visited:
            if dfs(node):
                # If dfs() returns True, a cycle was detected, so topological sort is not possible.
                return None

    # The `result` list is built by appending nodes *after* all their descendants are processed.
    # This means it's in reverse topological order. Reverse it to get the correct order.
    return result[::-1]
