# Daily Utility Snippets - 2026-06-04
# Generated by Gemini 1.5 Flash based on daily topics

import collections
from typing import List, Tuple, Dict, Deque

def build_adjacency_list(num_nodes: int, edges: List[Tuple[int, int]], directed: bool = False) -> Dict[int, List[int]]:
    """
    Builds an adjacency list representation of a graph from a list of edges.
    Initializes an entry for every node from 0 to num_nodes-1.

    Args:
        num_nodes: The total number of nodes in the graph. Nodes are assumed to be 0-indexed, from 0 to num_nodes - 1.
        edges: A list of tuples, where each tuple (u, v) represents an edge between node u and node v.
               Nodes in `edges` must be within the [0, num_nodes - 1] range.
        directed: If True, the graph is directed (u -> v); otherwise, it's undirected (u <-> v).

    Returns:
        A dictionary where keys are nodes (0 to num_nodes-1) and values are lists of their neighbors.
    
    Raises:
        ValueError: If an edge contains nodes outside the [0, num_nodes - 1] range.
    """
    adj: Dict[int, List[int]] = {i: [] for i in range(num_nodes)} # Initialize all nodes
    for u, v in edges:
        if not (0 <= u < num_nodes and 0 <= v < num_nodes):
            raise ValueError(f"Edge ({u}, {v}) contains nodes out of expected range [0, {num_nodes-1}].")
        adj[u].append(v)
        if not directed:
            adj[v].append(u)
    return adj

def bfs_shortest_paths(adj: Dict[int, List[int]], start_node: int) -> Dict[int, int]:
    """
    Performs a Breadth-First Search (BFS) to find the shortest distance from a
    given start node to all other reachable nodes in an unweighted graph.

    Args:
        adj: The adjacency list representation of the graph. Keys are nodes,
             values are lists of their neighbors.
        start_node: The node from which to start the BFS.

    Returns:
        A dictionary where keys are reachable nodes and values are their shortest
        distances from the start_node. If a node is unreachable, it will not
        be present in the dictionary. The start_node itself will have distance 0.
        Returns an empty dictionary if start_node is not present in the graph.
    """
    if start_node not in adj:
        return {}

    distances: Dict[int, int] = {start_node: 0}
    queue: Deque[int] = collections.deque([start_node])

    while queue:
        u = queue.popleft()
        for v in adj[u]:
            if v not in distances: # This implies v has not been visited yet
                distances[v] = distances[u] + 1
                queue.append(v)
    return distances

# Sample Use Case for build_adjacency_list and bfs_shortest_paths:
# if __name__ == '__main__':
#     # Example 1: Undirected graph
#     num_nodes_1 = 5
#     edges_1 = [(0, 1), (0, 2), (1, 3), (2, 3), (3, 4)]
#     
#     adj_list_1 = build_adjacency_list(num_nodes_1, edges_1, directed=False)
#     print(f"Adjacency List (Undirected): {adj_list_1}")
#     # Expected: {0: [1, 2], 1: [0, 3], 2: [0, 3], 3: [1, 2, 4], 4: [3]}
#
#     distances_from_0_1 = bfs_shortest_paths(adj_list_1, 0)
#     print(f"Shortest distances from node 0 (Undirected): {distances_from_0_1}")
#     # Expected: {0: 0, 1: 1, 2: 1, 3: 2, 4: 3}
#
#     distances_from_4_1 = bfs_shortest_paths(adj_list_1, 4)
#     print(f"Shortest distances from node 4 (Undirected): {distances_from_4_1}")
#     # Expected: {4: 0, 3: 1, 1: 2, 2: 2, 0: 3}
#
#     # Example 2: Directed graph
#     num_nodes_2 = 4
#     edges_2 = [(0, 1), (0, 2), (1, 3), (2, 3)]
#
#     adj_list_2 = build_adjacency_list(num_nodes_2, edges_2, directed=True)
#     print(f"\nAdjacency List (Directed): {adj_list_2}")
#     # Expected: {0: [1, 2], 1: [3], 2: [3], 3: []}
#
#     distances_from_0_2 = bfs_shortest_paths(adj_list_2, 0)
#     print(f"Shortest distances from node 0 (Directed): {distances_from_0_2}")
#     # Expected: {0: 0, 1: 1, 2: 1, 3: 2}
#
#     distances_from_3_2 = bfs_shortest_paths(adj_list_2, 3)
#     print(f"Shortest distances from node 3 (Directed): {distances_from_3_2}")
#     # Expected: {3: 0} (No outgoing edges, only 3 itself)
#
#     # Example 3: Disconnected graph / Node not in edges
#     num_nodes_3 = 5
#     edges_3 = [(0, 1), (1, 2)]
#     adj_list_3 = build_adjacency_list(num_nodes_3, edges_3, directed=False)
#     print(f"\nAdjacency List (Disconnected): {adj_list_3}")
#     # Expected: {0: [1], 1: [0, 2], 2: [1], 3: [], 4: []}
#
#     distances_from_0_3 = bfs_shortest_paths(adj_list_3, 0)
#     print(f"Shortest distances from node 0 (Disconnected): {distances_from_0_3}")
#     # Expected: {0: 0, 1: 1, 2: 2} (Nodes 3 and 4 are unreachable)
#
#     distances_from_non_existent = bfs_shortest_paths(adj_list_3, 99)
#     print(f"Shortest distances from non-existent node 99: {distances_from_non_existent}")
#     # Expected: {}
#
#     # Example 4: Edge case for build_adjacency_list (out-of-bounds node)
#     # try:
#     #     build_adjacency_list(3, [(0, 1), (1, 4)])
#     # except ValueError as e:
#     #     print(f"\nError building adjacency list: {e}")
#     # Expected: Error building adjacency list: Edge (1, 4) contains nodes out of expected range [0, 2].
