# Daily Utility Snippets - 2026-05-28
# Generated by Gemini 1.5 Flash based on daily topics

import math
from typing import Callable, List, Tuple

def sieve_of_eratosthenes(limit: int) -> List[bool]:
    """
    Generates a boolean list indicating primality for numbers up to a given limit
    using the Sieve of Eratosthenes algorithm.

    The Sieve of Eratosthenes is an efficient algorithm for finding all prime
    numbers up to any given limit. It works by iteratively marking as composite
    (i.e., not prime) the multiples of each prime, starting with the first prime
    number, 2. The unmarked numbers remaining are prime.

    Args:
        limit: An integer representing the upper bound (inclusive) for finding primes.
               Numbers from 0 to `limit` will be checked. Must be non-negative.

    Returns:
        A list of booleans, `is_prime`, where `is_prime[i]` is True if `i` is a
        prime number, and False otherwise. The list has `limit + 1` elements.

    Raises:
        ValueError: If `limit` is negative.

    Examples:
        >>> sieve_of_eratosthenes(10)
        [False, False, True, True, False, True, False, True, False, False, False]
        # Explanation:
        # is_prime[0] = False (not prime)
        # is_prime[1] = False (not prime)
        # is_prime[2] = True  (prime)
        # is_prime[3] = True  (prime)
        # is_prime[4] = False (2*2)
        # is_prime[5] = True  (prime)
        # is_prime[6] = False (2*3)
        # is_prime[7] = True  (prime)
        # is_prime[8] = False (2*4)
        # is_prime[9] = False (3*3)
        # is_prime[10] = False (2*5)
    """
    if limit < 0:
        raise ValueError("Limit must be a non-negative integer.")

    is_prime: List[bool] = [True] * (limit + 1)
    if limit >= 0:
        is_prime[0] = False  # 0 is not prime
    if limit >= 1:
        is_prime[1] = False  # 1 is not prime

    # Iterate from 2 up to sqrt(limit)
    # Any composite number n must have at least one prime factor less than or equal to sqrt(n)
    for p in range(2, int(math.sqrt(limit)) + 1):
        # If p is prime (not marked False yet)
        if is_prime[p]:
            # Mark all multiples of p as not prime.
            # We can start from p*p because any multiple k*p where k < p would have
            # already been marked by a smaller prime factor than p.
            for multiple in range(p * p, limit + 1, p):
                is_prime[multiple] = False
    return is_prime

# Sample Use Case:
# # To find all prime numbers up to 100:
# primes_up_to_100_map = sieve_of_eratosthenes(100)
# prime_numbers_list = [i for i, is_p in enumerate(primes_up_to_100_map) if is_p]
# # print(prime_numbers_list) # Output: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, ..., 97]

def binary_search_first_true(
    low: int, high: int, predicate: Callable[[int], bool]
) -> int:
    """
    Performs a binary search to find the smallest integer `x` within a given
    range `[low, high]` for which a `predicate(x)` evaluates to True.

    This function is useful when searching for a threshold value where a condition
    switches from False to True. The `predicate` function must exhibit a
    monotonic property: if `predicate(x)` is True, then `predicate(y)` must also
    be True for all `y > x`. Conversely, if `predicate(x)` is False, then
    `predicate(y)` must also be False for all `y < x`. The typical pattern is
    `F F F ... T T T`.

    Args:
        low: The lower bound (inclusive) of the search range.
        high: The upper bound (inclusive) of the search range.
        predicate: A callable (function or lambda) that takes an integer `x`
                   and returns a boolean. It should be monotonically non-decreasing.

    Returns:
        The smallest integer `x` in `[low, high]` such that `predicate(x)` is True.
        Returns `high + 1` if no such `x` exists in the range `[low, high]`
        (meaning all values in `[low, high]` result in False for the predicate,
        or the range is empty). This `high + 1` value indicates that the "first true"
        value is effectively "out of bounds" on the right. If the first true value
        is `low`, it returns `low`.

    Examples:
        # Predicate: `x >= 6` (monotonic non-decreasing: F F F F F F T T T T T)
        # Search range [0, 10]
        >>> def is_sufficient(x: int) -> bool:
        ...     return x >= 6
        >>> binary_search_first_true(0, 10, is_sufficient)
        6

        # All values in the range are False (e.g., search [0, 5] for `x >= 6`)
        >>> binary_search_first_true(0, 5, is_sufficient)
        6 # (high + 1, indicating no value in [0, 5] satisfies the predicate)

        # All values in the range are True (e.g., search [0, 10] for `x >= 0`)
        >>> binary_search_first_true(0, 10, lambda x: x >= 0)
        0

        # Empty range (low > high)
        >>> binary_search_first_true(5, 0, lambda x: True)
        1 # (high + 1, as if no value found)
    """
    ans = high + 1  # Initialize with a value indicating 'not found'
    # This also serves as the potential answer if all elements are false or range is empty.

    while low <= high:
        mid = low + (high - low) // 2
        if predicate(mid):
            ans = mid  # mid could be the answer, try to find an even smaller one
            high = mid - 1
        else:
            low = mid + 1
    return ans

# Sample Use Case:
# # Problem: Given `weights` of items and a number of `days`, find the minimum
# # capacity `C` for a boat such that all items can be shipped within `D` days.
#
# # Helper predicate function:
# def can_ship_within_days(capacity: int, weights: List[int], days: int) -> bool:
#     current_load = 0
#     days_needed = 1
#     for weight in weights:
#         if weight > capacity: # A single item is too heavy for this capacity
#             return False
#         if current_load + weight <= capacity:
#             current_load += weight
#         else: # Must start a new day/trip
#             days_needed += 1
#             current_load = weight
#     return days_needed <= days
#
# ship_weights_example = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# ship_days_example = 5
#
# # The search space for capacity is from the max single item weight to the sum of all weights.
# min_possible_capacity = max(ship_weights_example)
# max_possible_capacity = sum(ship_weights_example)
#
# # Create a predicate function suitable for `binary_search_first_true` by binding
# # the `weights` and `days` arguments.
# import functools
# find_capacity_predicate = functools.partial(
#     can_ship_within_days, weights=ship_weights_example, days=ship_days_example
# )
#
# minimum_shipping_capacity = binary_search_first_true(
#     min_possible_capacity, max_possible_capacity, find_capacity_predicate
# )
# # print(f"Minimum shipping capacity: {minimum_shipping_capacity}") # Output: Minimum shipping capacity: 15
