# Daily Utility Snippets - 2026-07-02
# Generated by Gemini 1.5 Flash based on daily topics

from collections import deque
from typing import Dict, List, Optional, TypeVar, Set

# Type variable for nodes/elements in the graph or Union-Find structure
N = TypeVar('N')

def bfs_shortest_path(
    graph: Dict[N, List[N]],
    start_node: N,
    target_node: Optional[N] = None
) -> Optional[List[N]]:
    """
    Performs a Breadth-First Search (BFS) to find the shortest path from a start node
    to a target node in an unweighted graph.

    Args:
        graph: An adjacency list representation of the graph, where keys are nodes
               and values are lists of their neighbors.
        start_node: The node from which to start the BFS.
        target_node: The node to find the shortest path to. If None, the function
                     will traverse the graph from start_node but will return None
                     as no specific target path is requested.

    Returns:
        A list of nodes representing the shortest path from start_node to target_node,
        inclusive. Returns None if the target_node is not reachable or not specified.

    Raises:
        ValueError: If start_node is not in the graph.
    """
    if start_node not in graph:
        raise ValueError(f"Start node '{start_node}' not found in the graph.")

    queue: deque[N] = deque([start_node])
    visited: Set[N] = {start_node}
    predecessors: Dict[N, N] = {} # To reconstruct the path

    while queue:
        current_node = queue.popleft()

        if target_node is not None and current_node == target_node:
            # Reconstruct path
            path: List[N] = []
            node = target_node
            # Walk back from target to start using predecessors
            while node != start_node:
                path.append(node)
                node = predecessors[node]
            path.append(start_node)
            return path[::-1] # Reverse to get path from start to target

        for neighbor in graph.get(current_node, []):
            if neighbor not in visited:
                visited.add(neighbor)
                predecessors[neighbor] = current_node
                queue.append(neighbor)

    return None # Target not reachable or target_node was None

# Sample Use Case for bfs_shortest_path
# graph1 = {
#     'A': ['B', 'C'],
#     'B': ['D', 'E'],
#     'C': ['F'],
#     'D': [],
#     'E': ['F'],
#     'F': []
# }
# path = bfs_shortest_path(graph1, 'A', 'F')
# # print(f"Path from A to F: {path}") # Expected: ['A', 'C', 'F'] (or similar shortest path)

# path_no_exist = bfs_shortest_path(graph1, 'A', 'G')
# # print(f"Path from A to G: {path_no_exist}") # Expected: None

# try:
#     bfs_shortest_path(graph1, 'Z', 'A')
# except ValueError as e:
#     # print(e) # Expected: Start node 'Z' not found in the graph.
#     pass


class UnionFind:
    """
    A Disjoint Set Union (Union-Find) data structure with path compression and
    union by size heuristics.

    It efficiently manages a collection of disjoint sets, allowing for two primary
    operations:
    1.  `find(element)`: Determines the representative (root) of the set containing
        the given element. This operation also performs path compression to flatten
        the tree structure.
    2.  `union(element1, element2)`: Merges the sets containing element1 and element2
        into a single set. This operation uses union by size to keep the trees balanced.

    Elements not present during initialization can be added dynamically when `find`
    or `union` is called on them.
    """
    _parent: Dict[N, N]
    _size: Dict[N, int] # Stores the size of the set rooted at an element

    def __init__(self, elements: Optional[List[N]] = None):
        """
        Initializes the Union-Find structure.
        If a list of elements is provided, each element is initially in its own set.
        Otherwise, it starts empty, and elements are added dynamically.
        """
        self._parent = {}
        self._size = {}
        if elements:
            for e in elements:
                self._parent[e] = e
                self._size[e] = 1

    def _ensure_element_exists(self, element: N) -> None:
        """Helper to add an element to the structure if it doesn't exist."""
        if element not in self._parent:
            self._parent[element] = element
            self._size[element] = 1

    def find(self, element: N) -> N:
        """
        Finds the representative (root) of the set containing the given element.
        Performs path compression for efficiency.

        Args:
            element: The element whose set representative is to be found.

        Returns:
            The representative element of the set.
        """
        self._ensure_element_exists(element)
        if self._parent[element] == element:
            return element
        self._parent[element] = self.find(self._parent[element]) # Path compression
        return self._parent[element]

    def union(self, element1: N, element2: N) -> bool:
        """
        Merges the sets containing element1 and element2.
        Uses union by size heuristic to keep trees balanced.

        Args:
            element1: An element from the first set.
            element2: An element from the second set.

        Returns:
            True if the two elements were in different sets and were successfully
            merged, False otherwise (i.e., they were already in the same set).
        """
        self._ensure_element_exists(element1)
        self._ensure_element_exists(element2)

        root1 = self.find(element1)
        root2 = self.find(element2)

        if root1 != root2:
            # Union by size: attach smaller tree to root of larger tree
            if self._size[root1] < self._size[root2]:
                self._parent[root1] = root2
                self._size[root2] += self._size[root1]
            else:
                self._parent[root2] = root1
                self._size[root1] += self._size[root2]
            return True
        return False # Elements were already in the same set

    def get_num_sets(self) -> int:
        """
        Returns the current number of disjoint sets.
        """
        # Count elements that are their own parent (i.e., roots of sets)
        return sum(1 for e, p in self._parent.items() if e == p)

    def get_set_size(self, element: N) -> int:
        """
        Returns the size of the set containing the given element.
        Finds the root first to ensure path compression and correct size.
        """
        root = self.find(element)
        return self._size[root]

# Sample Use Case for UnionFind
# uf = UnionFind(list(range(5))) # Initialize with elements 0-4
# # print(f"Initial number of sets: {uf.get_num_sets()}") # Expected: 5

# uf.union(0, 1) # Merge 0 and 1
# # print(f"Union(0, 1), num sets: {uf.get_num_sets()}") # Expected: 4
# uf.union(2, 3) # Merge 2 and 3
# # print(f"Union(2, 3), num sets: {uf.get_num_sets()}") # Expected: 3
# uf.union(0, 2) # Merge the set of (0,1) with the set of (2,3)
# # print(f"Union(0, 2), num sets: {uf.get_num_sets()}") # Expected: 2

# # Check connectivity
# # print(f"Are 1 and 3 connected? {uf.find(1) == uf.find(3)}") # Expected: True
# # print(f"Are 1 and 4 connected? {uf.find(1) == uf.find(4)}") # Expected: False

# # Check set sizes
# # print(f"Size of set containing 0: {uf.get_set_size(0)}") # Expected: 4 (elements 0,1,2,3)
# # print(f"Size of set containing 4: {uf.get_set_size(4)}") # Expected: 1

# # Test dynamic element addition
# uf_dynamic = UnionFind()
# uf_dynamic.union('a', 'b') # Adds 'a' and 'b', then unions them
# # print(f"Dynamic UF sets after ('a','b') union: {uf_dynamic.get_num_sets()}") # Expected: 1
# uf_dynamic.find('c') # Adds 'c'
# # print(f"Dynamic UF sets after find('c'): {uf_dynamic.get_num_sets()}") # Expected: 2 ('a','b' set, 'c' set)
# uf_dynamic.union('a', 'c')
# # print(f"Dynamic UF sets after ('a','c') union: {uf_dynamic.get_num_sets()}") # Expected: 1 ('a','b','c' set)
# # print(f"Size of set containing 'a': {uf_dynamic.get_set_size('a')}") # Expected: 3
