# Daily Utility Snippets - 2026-05-23
# Generated by Gemini 1.5 Flash based on daily topics

import operator
import random
from typing import Callable, List, Generic, TypeVar, Tuple

# Type variable for Segment Tree's data type
T = TypeVar('T')

class StringHasher:
    """
    A utility class for efficient O(1) substring hash calculation using polynomial rolling hash.
    It employs double hashing (two different bases and moduli) to minimize collision probability.
    This is highly useful for string matching, finding palindromes, or solving problems
    that require quick comparison of substrings.
    """
    # Use fixed, large prime moduli and bases for consistency and good distribution.
    # It's common practice in competitive programming to use these or similar fixed values
    # rather than random ones to ensure deterministic behavior across runs.
    _BASES = (31, 37)  # Two distinct small prime bases
    _MODULI = (1_000_000_007, 1_000_000_009) # Two distinct large prime moduli

    def __init__(self, s: str):
        """
        Initializes the StringHasher for a given string.
        Precomputes prefix hashes and powers of bases in O(N) time.

        Args:
            s: The input string for which to compute hashes.
        """
        self.n = len(s)
        # _prefix_hashes[i][j] stores the hash of s[0...j-1] for the i-th hash function.
        self._prefix_hashes: List[List[int]] = [[0] * (self.n + 1) for _ in range(2)]
        # _powers[i][j] stores (base_i)^j % modulus_i.
        self._powers: List[List[int]] = [[1] * (self.n + 1) for _ in range(2)]

        for i in range(2):
            base = StringHasher._BASES[i]
            mod = StringHasher._MODULI[i]
            
            for j in range(self.n):
                # Calculate prefix hash: H(s[0...j]) = (H(s[0...j-1]) * base + ord(s[j])) % mod
                self._prefix_hashes[i][j+1] = (self._prefix_hashes[i][j] * base + ord(s[j])) % mod
                # Calculate powers of base: base^j = (base^(j-1) * base) % mod
                self._powers[i][j+1] = (self._powers[i][j] * base) % mod

    def get_hash(self, left: int, right: int) -> Tuple[int, int]:
        """
        Calculates the rolling hash of the substring s[left:right+1] (inclusive indices).
        Returns a tuple of two hashes (for double hashing) in O(1) time.

        The hash of a substring s[left...right] is computed using the formula:
        H(s[left...right]) = (prefix_hash[right+1] - prefix_hash[left] * powers[length]) % mod
        where length = right - left + 1.

        Args:
            left: The 0-based starting index of the substring.
            right: The 0-based ending index of the substring (inclusive).

        Returns:
            A tuple (hash1, hash2) representing the double hash of the substring.

        Raises:
            ValueError: If left or right indices are out of bounds or left > right.
        """
        if not (0 <= left <= right < self.n):
            raise ValueError(f"Invalid indices: left={left}, right={right} for string of length {self.n}")

        hash_values = []
        substring_length = right - left + 1

        for i in range(2):
            mod = StringHasher._MODULI[i]
            
            # Calculate the hash using prefix hashes and powers.
            # (A - B % M + M) % M is used to correctly handle negative results from subtraction.
            h = (self._prefix_hashes[i][right+1] - \
                 (self._prefix_hashes[i][left] * self._powers[i][substring_length]) % mod + mod) % mod
            hash_values.append(h)
            
        return tuple(hash_values)

# Sample Usage for StringHasher:
# string_to_hash = "abracadabra"
# hasher = StringHasher(string_to_hash)
#
# # Get hash of "abra" (indices 0 to 3, inclusive)
# hash_abra1 = hasher.get_hash(0, 3)
#
# # Get hash of "abra" (indices 7 to 10, inclusive)
# hash_abra2 = hasher.get_hash(7, 10)
#
# print(f"Hash of 'abra' at [0,3]: {hash_abra1}")
# print(f"Hash of 'abra' at [7,10]: {hash_abra2}")
# print(f"Are 'abra' substrings at different positions equal? {hash_abra1 == hash_abra2}") # Expected: True
#
# # Get hash of "cad" (indices 4 to 6, inclusive)
# hash_cad = hasher.get_hash(4, 6)
# print(f"Hash of 'cad' at [4,6]: {hash_cad}")
#
# # Verify a substring does not match
# print(f"Is 'cad' equal to 'abra'? {hash_cad == hash_abra1}") # Expected: False
#
# # Example: Find all occurrences of a pattern
# pattern = "ra"
# pattern_hasher = StringHasher(pattern) # Create a hasher for the pattern itself
# pattern_hash = pattern_hasher.get_hash(0, len(pattern) - 1)
#
# print(f"Occurrences of '{pattern}':")
# for i in range(hasher.n - len(pattern) + 1):
#     if hasher.get_hash(i, i + len(pattern) - 1) == pattern_hash:
#         print(f"  Found at index {i}") # Expected: 2, 9


class SegmentTree(Generic[T]):
    """
    A generic Segment Tree implementation for efficient range queries and point updates.
    It supports any associative aggregation function (e.g., sum, min, max, GCD).
    This data structure is fundamental for problems involving array range queries,
    dynamic programming optimizations, and certain graph algorithms.
    """
    def __init__(self, data: List[T], func: Callable[[T, T], T], default_value: T):
        """
        Initializes the Segment Tree.
        Time complexity: O(N) to build the tree.

        Args:
            data: The initial list of values. The tree will be built over this data.
            func: An associative function (e.g., operator.add, min, max, operator.gcd)
                  used for aggregation. It must satisfy func(a, func(b, c)) == func(func(a, b), c).
            default_value: The identity element for the 'func'.
                           E.g., 0 for sum, float('inf') for min, float('-inf') for max, 0 for GCD.
        """
        self.n = len(data)
        self.func = func
        self.default_value = default_value
        # The tree array uses 1-based indexing conceptually, with leaves at indices n to 2n-1.
        # This allows for simpler parent/child calculations (parent of i is i//2, children are 2i, 2i+1).
        # We allocate 2*n space to accommodate this structure.
        self.tree: List[T] = [default_value] * (2 * self.n)

        if self.n == 0:
            return

        # Initialize leaves of the tree with the input data.
        # The actual data elements are stored starting from index `self.n`.
        for i in range(self.n):
            self.tree[self.n + i] = data[i]

        # Build the rest of the tree by aggregating up from the leaves.
        # Nodes at index `i` store the aggregation of their children `2*i` and `2*i+1`.
        for i in range(self.n - 1, 0, -1):
            self.tree[i] = self.func(self.tree[2 * i], self.tree[2 * i + 1])

    def update(self, index: int, value: T) -> None:
        """
        Updates the value at a specific index in the original data array.
        Then, it updates all ancestors of that index in the tree.
        Time complexity: O(log N).

        Args:
            index: The 0-based index of the element to update.
            value: The new value for the element.

        Raises:
            IndexError: If the index is out of bounds.
        """
        if not (0 <= index < self.n):
            raise IndexError(f"Index {index} out of bounds for data of length {self.n}")

        # Map the 0-based data index to the 1-based tree array index for leaves.
        pos = self.n + index
        self.tree[pos] = value
        
        # Traverse up to the root, updating each parent node.
        # `pos // 2` gives the parent. `pos ^ 1` gives the sibling node (if pos is left child, pos+1; if right, pos-1).
        while pos > 1:
            self.tree[pos // 2] = self.func(self.tree[pos], self.tree[pos ^ 1])
            pos //= 2

    def query(self, left: int, right: int) -> T:
        """
        Queries the aggregated value for a given range [left, right) (exclusive of right).
        This means the query includes `left` but excludes `right`.
        Time complexity: O(log N).

        Args:
            left: The 0-based starting index of the range (inclusive).
            right: The 0-based ending index of the range (exclusive).

        Returns:
            The aggregated value for the specified range.
            Returns `default_value` if the range is empty (left == right).

        Raises:
            ValueError: If left or right indices are out of bounds or left > right.
        """
        if not (0 <= left <= right <= self.n):
            raise ValueError(f"Invalid range: left={left}, right={right} for data of length {self.n}")
        if left == right:
            return self.default_value # Empty range

        res = self.default_value
        # Map 0-based query indices to 1-based tree array indices for leaves.
        left += self.n
        right += self.n

        # Traverse the tree to find the required segments.
        # The loop stops when 'left' and 'right' pointers meet.
        while left < right:
            # If 'left' is a right child, it means its parent does not fully cover the range
            # from 'left' upwards. So, include 'left' itself and move to its sibling's parent.
            if left % 2 == 1:
                res = self.func(res, self.tree[left])
                left += 1
            # If 'right' is a right child, it means it's the rightmost node in a covered segment.
            # Include 'right-1' (its sibling, which is a left child) and move to its parent.
            if right % 2 == 1:
                right -= 1
                res = self.func(res, self.tree[right])
            
            # Move up to the parent level.
            left //= 2
            right //= 2
        return res

# Sample Usage for SegmentTree:
# Example 1: Sum Segment Tree
# initial_data_sum = [1, 3, 5, 7, 9, 11]
# sum_tree = SegmentTree(initial_data_sum, operator.add, 0)
#
# # Query sum of [0, 6) -> 1+3+5+7+9+11 = 36
# print(f"Sum of [0, 6): {sum_tree.query(0, 6)}") # Expected: 36
#
# # Query sum of [2, 5) -> 5+7+9 = 21
# print(f"Sum of [2, 5): {sum_tree.query(2, 5)}") # Expected: 21
#
# # Update index 2 from 5 to 10
# sum_tree.update(2, 10) # Original data is now effectively [1, 3, 10, 7, 9, 11]
#
# # Query sum of [2, 5) again -> 10+7+9 = 26
# print(f"Sum of [2, 5) after update: {sum_tree.query(2, 5)}") # Expected: 26
#
# # Example 2: Min Segment Tree
# initial_data_min = [5, 2, 8, 1, 9, 3]
# min_tree = SegmentTree(initial_data_min, min, float('inf'))
#
# # Query min of [0, 6) -> min(5,2,8,1,9,3) = 1
# print(f"Min of [0, 6): {min_tree.query(0, 6)}") # Expected: 1
#
# # Query min of [1, 4) -> min(2, 8, 1) = 1
# print(f"Min of [1, 4): {min_tree.query(1, 4)}") # Expected: 1
#
# # Update index 3 from 1 to 10
# min_tree.update(3, 10) # Original data is now effectively [5, 2, 8, 10, 9, 3]
#
# # Query min of [1, 4) again -> min(2, 8, 10) = 2
# print(f"Min of [1, 4) after update: {min_tree.query(1, 4)}") # Expected: 2
#
# # Example 3: Max Segment Tree
# initial_data_max = [5, 2, 8, 1, 9, 3]
# max_tree = SegmentTree(initial_data_max, max, float('-inf'))
# print(f"Max of [0, 6): {max_tree.query(0, 6)}") # Expected: 9
# max_tree.update(1, 12) # Update index 1 from 2 to 12
# print(f"Max of [0, 6) after update: {max_tree.query(0, 6)}") # Expected: 12
