# Daily Utility Snippets - 2026-05-30
# Generated by Gemini 1.5 Flash based on daily topics

import collections
from typing import Any, Deque, Dict, List, Optional, Tuple, Set

# --- UTILITY FUNCTION 1: Binary Tree Level-Order Traversal ---

class TreeNode:
    """Definition for a binary tree node.
    This class is typically provided in competitive programming problems or
    is a standard building block for tree-related algorithms.
    """
    def __init__(self, val: Any = 0, left: Optional['TreeNode'] = None, right: Optional['TreeNode'] = None):
        self.val = val
        self.left = left
        self.right = right

def level_order_traversal(root: Optional[TreeNode]) -> List[List[Any]]:
    """
    Performs a level-order (Breadth-First Search) traversal of a binary tree.

    This function is extremely useful for:
    - Serializing/deserializing trees.
    - Solving problems that require processing nodes level by level (e.g., finding the
      maximum value in each level, connecting nodes at the same level, etc.).

    Args:
        root: The root node of the binary tree. Can be None for an empty tree.

    Returns:
        A list of lists, where each inner list contains the values of nodes
        at a particular level, ordered from root to leaves, and from left to right
        within each level. Returns an empty list if the tree is empty.
    """
    if not root:
        return []

    result: List[List[Any]] = []
    queue: Deque[TreeNode] = collections.deque([root])

    while queue:
        level_size = len(queue)
        current_level_values: List[Any] = []
        for _ in range(level_size):
            node = queue.popleft()
            current_level_values.append(node.val)

            if node.left:
                queue.append(node.left)
            if node.right:
                queue.append(node.right)
        result.append(current_level_values)

    return result

# Sample Use Case for level_order_traversal:
# Construct a sample tree:
#       3
#      / \
#     9  20
#       /  \
#      15   7
# root = TreeNode(3)
# root.left = TreeNode(9)
# root.right = TreeNode(20)
# root.right.left = TreeNode(15)
# root.right.right = TreeNode(7)
# print(level_order_traversal(root))
# Expected: [[3], [9, 20], [15, 7]]

# Empty tree:
# print(level_order_traversal(None))
# Expected: []


# --- UTILITY FUNCTION 2: Graph Shortest Path BFS (Unweighted) ---

def bfs_shortest_path(
    graph: Dict[Any, List[Any]],
    start_node: Any
) -> Tuple[Dict[Any, int], Dict[Any, Optional[Any]]]:
    """
    Performs a Breadth-First Search (BFS) to find the shortest distance and
    predecessor path from a given start node in an unweighted graph.

    This function is extremely useful for:
    - Finding the minimum number of edges to reach any node from a source.
    - Detecting reachability between nodes.
    - Reconstructing a shortest path.
    - Solving various graph problems like shortest path in a maze, connected components,
      or flood fill, where edge weights are uniform (or absent).

    Args:
        graph: An adjacency list representation of the graph. Keys are nodes,
               values are lists of neighboring nodes. Nodes must be hashable.
               Assumes undirected graph if (u, v) implies (v, u) in adjacency lists,
               or directed if only (u, v) is present.
        start_node: The node from which to start the BFS. It must be a hashable type.

    Returns:
        A tuple containing two dictionaries:
        1. distances: Maps each reachable node to its shortest distance (number of edges)
           from the start_node. Nodes not reachable from start_node will not be in this dictionary.
        2. predecessors: Maps each reachable node (except start_node itself) to its direct
           predecessor node on one of the shortest paths from start_node. This can be used
           to reconstruct the path. The start_node will map to None.
           If a node is unreachable, it will not be in this dictionary.
    """
    distances: Dict[Any, int] = {}
    predecessors: Dict[Any, Optional[Any]] = {}
    queue: Deque[Any] = collections.deque()

    # Initialize for the start node
    if start_node in graph or any(start_node in neighbors for neighbors in graph.values()):
        # Only add to queue if start_node is a known node in the graph,
        # either as a key or as a neighbor.
        distances[start_node] = 0
        predecessors[start_node] = None
        queue.append(start_node)
    else:
        # If start_node is not part of the graph at all, it's an isolated component of size 1.
        return {start_node: 0}, {start_node: None}

    while queue:
        current_node = queue.popleft()

        # Iterate over neighbors. graph.get handles cases where current_node might be
        # a sink node (no outgoing edges) or an isolated node defined only as a neighbor.
        for neighbor in graph.get(current_node, []):
            if neighbor not in distances: # Check if the neighbor has been visited/processed
                distances[neighbor] = distances[current_node] + 1
                predecessors[neighbor] = current_node
                queue.append(neighbor)

    return distances, predecessors

# Sample Use Case for bfs_shortest_path:
# Define a sample graph (adjacency list) for an undirected graph:
# Graph visualization:
# A -- B -- D
# |    |
# C -- E
# F (isolated node)
# graph = {
#     'A': ['B', 'C'],
#     'B': ['A', 'D', 'E'],
#     'C': ['A', 'E'],
#     'D': ['B'],
#     'E': ['B', 'C'],
#     'F': [] # Isolated node
# }

# From node 'A':
# distances_a, preds_a = bfs_shortest_path(graph, 'A')
# print("Distances from 'A':", distances_a)
# Expected: {'A': 0, 'B': 1, 'C': 1, 'D': 2, 'E': 2}
# print("Predecessors from 'A':", preds_a)
# Expected: {'A': None, 'B': 'A', 'C': 'A', 'D': 'B', 'E': 'B'} (or 'E': 'C' also valid)

# From isolated node 'F':
# distances_f, preds_f = bfs_shortest_path(graph, 'F')
# print("Distances from 'F':", distances_f)
# Expected: {'F': 0}
# print("Predecessors from 'F':", preds_f)
# Expected: {'F': None}

# From a node not explicitly defined as a key but as a neighbor (e.g., if 'G' was only in 'H': ['G'])
# Let's assume a node 'X' that is not in the graph at all:
# distances_x, preds_x = bfs_shortest_path(graph, 'X')
# print("Distances from 'X':", distances_x)
# Expected: {'X': 0}
# print("Predecessors from 'X':", preds_x)
# Expected: {'X': None}
