# Daily Utility Snippets - 2026-05-22
# Generated by Gemini 1.5 Flash based on daily topics

import math
from typing import List, Optional

def modular_inverse(a: int, m: int) -> Optional[int]:
    """
    Calculates the modular multiplicative inverse of 'a' modulo 'm'.

    This function finds an integer 'x' such that (a * x) % m == 1.
    It primarily uses Fermat's Little Theorem, which requires 'm' to be a
    prime number and 'a' not to be a multiple of 'm'. For competitive
    programming contexts, 'm' is almost always a prime number (e.g., 10^9 + 7).

    Args:
        a: The integer for which to find the inverse. Must be non-negative.
        m: The prime modulus. Must be a positive prime number.

    Returns:
        The modular inverse of 'a' modulo 'm' if it exists, otherwise None.
        Returns None if 'a' is a multiple of 'm', or if 'm' is not positive
        or not prime (as Fermat's Little Theorem would not apply).

    Raises:
        ValueError: If m is not positive or a is negative.

    # Sample Use Case 1: Finding inverse of 3 mod 7
    # inv = modular_inverse(3, 7) # inv will be 5 (since 3 * 5 = 15, 15 % 7 = 1)
    # print(f"Inverse of 3 mod 7: {inv}")

    # Sample Use Case 2: For a large prime modulus
    # MOD = 10**9 + 7
    # inv_large = modular_inverse(12345, MOD)
    # print(f"Inverse of 12345 mod {MOD}: {inv_large}")

    # Sample Use Case 3: When inverse does not exist (modulus not prime)
    # inv_none_non_prime = modular_inverse(4, 8) # inv_none_non_prime will be None
    # print(f"Inverse of 4 mod 8: {inv_none_non_prime}")

    # Sample Use Case 4: When inverse does not exist (a is a multiple of m)
    # inv_none_multiple = modular_inverse(7, 7) # inv_none_multiple will be None
    # print(f"Inverse of 7 mod 7: {inv_none_multiple}")
    """
    if m <= 0:
        raise ValueError("Modulus 'm' must be a positive prime number.")
    if a < 0:
        raise ValueError("Integer 'a' must be non-negative.")

    # An inverse exists if and only if gcd(a, m) == 1.
    # If m is prime, gcd(a, m) == 1 if a is not a multiple of m.
    if a % m == 0:
        return None
    
    # Fermat's Little Theorem: If m is a prime number, then for any integer a
    # not divisible by m, a^(m-1) ≡ 1 (mod m).
    # This implies a * a^(m-2) ≡ 1 (mod m).
    # Thus, a^(m-2) is the modular inverse.
    return pow(a, m - 2, m)

def sieve_of_eratosthenes(limit: int) -> List[int]:
    """
    Generates a list of prime numbers up to a specified limit using the
    Sieve of Eratosthenes algorithm.

    The Sieve of Eratosthenes is an efficient algorithm for finding all prime
    numbers up to any given limit. It does so by iteratively marking as
    composite (i.e., not prime) the multiples of each prime, starting with 2.

    Args:
        limit: The upper bound (inclusive) for finding prime numbers.
               Must be a non-negative integer.

    Returns:
        A list of prime numbers up to the specified limit, in ascending order.

    Raises:
        ValueError: If limit is negative.

    # Sample Use Case 1: Primes up to 20
    # primes_up_to_20 = sieve_of_eratosthenes(20)
    # print(f"Primes up to 20: {primes_up_to_20}") # Expected: [2, 3, 5, 7, 11, 13, 17, 19]

    # Sample Use Case 2: Primes up to 0 or 1
    # primes_up_to_0 = sieve_of_eratosthenes(0)
    # print(f"Primes up to 0: {primes_up_to_0}") # Expected: []
    # primes_up_to_1 = sieve_of_eratosthenes(1)
    # print(f"Primes up to 1: {primes_up_to_1}") # Expected: []

    # Sample Use Case 3: Larger limit
    # primes_up_to_100 = sieve_of_eratosthenes(100)
    # print(f"Primes up to 100 (first 10): {primes_up_to_100[:10]}...") # Expected: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]...
    """
    if limit < 0:
        raise ValueError("Limit must be a non-negative integer.")
    if limit < 2:
        return []

    # Create a boolean array "is_prime[0..limit]" and initialize
    # all entries it as true. A value in is_prime[i] will
    # finally be false if i is Not a prime, else true.
    is_prime = [True] * (limit + 1)
    is_prime[0] = is_prime[1] = False  # 0 and 1 are not prime numbers

    # Start from p=2. If is_prime[p] is still true, then it is a prime.
    # Mark all multiples of p greater than or equal to p*p as false.
    # Multiples less than p*p would have already been marked.
    for p in range(2, int(math.sqrt(limit)) + 1):
        if is_prime[p]:
            # Update all multiples of p starting from p*p
            for multiple in range(p * p, limit + 1, p):
                is_prime[multiple] = False

    # Collect all prime numbers
    primes = [p for p in range(2, limit + 1) if is_prime[p]]
    return primes
