# Daily Utility Snippets - 2026-05-29
# Generated by Gemini 1.5 Flash based on daily topics

from typing import List, Tuple, Dict, Set

def sieve_of_eratosthenes(n: int) -> List[bool]:
    """
    Generates a boolean list indicating primality for numbers up to n using the Sieve of Eratosthenes.

    A number `i` is prime if `is_prime[i]` is True.
    The list is 0-indexed, where `is_prime[0]` and `is_prime[1]` are always False.

    Args:
        n: The upper limit (inclusive) for checking primality. Must be a non-negative integer.

    Returns:
        A list of booleans, where `is_prime[i]` is True if `i` is prime, False otherwise.

    Raises:
        ValueError: If n is negative.

    # Sample Use Case 1: Get primes up to a certain number
    # is_prime_list = sieve_of_eratosthenes(30)
    # print(is_prime_list[0:20])
    # # Expected: [False, False, True, True, False, True, False, True, False, False, False, True, False, True, False, False, False, True, False, True]
    #
    # primes_up_to_10 = [i for i, is_p in enumerate(is_prime_list) if is_p and i <= 10]
    # print(primes_up_to_10)
    # # Expected: [2, 3, 5, 7]
    #
    # Sample Use Case 2: Check primality of specific numbers
    # primes_sieve = sieve_of_eratosthenes(100)
    # print(primes_sieve[97]) # Expected: True
    # print(primes_sieve[91]) # Expected: False (91 = 7 * 13)
    """
    if n < 0:
        raise ValueError("n must be a non-negative integer.")

    if n < 2:
        return [False] * (n + 1)

    is_prime = [True] * (n + 1)
    is_prime[0] = is_prime[1] = False  # 0 and 1 are not prime

    # Iterate from 2 up to the square root of n
    for p in range(2, int(n**0.5) + 1):
        if is_prime[p]:
            # Mark multiples of p (starting from p*p) as not prime
            for multiple in range(p * p, n + 1, p):
                is_prime[multiple] = False
    return is_prime


def build_adjacency_list(
    num_nodes: int,
    edges: List[Tuple[int, int]],
    is_directed: bool = False,
    is_one_indexed: bool = False
) -> Dict[int, List[int]]:
    """
    Builds an adjacency list representation of a graph from a list of edges.

    An adjacency list maps each node to a list of its direct neighbors.
    The resulting adjacency list will always use 0-indexed node IDs internally.

    Args:
        num_nodes: The total number of nodes in the graph. Nodes are assumed to be
                   0-indexed (0 to num_nodes-1) or 1-indexed (1 to num_nodes)
                   based on `is_one_indexed`.
        edges: A list of tuples, where each tuple (u, v) represents an edge
               between node u and node v.
        is_directed: If True, edges are (u -> v). If False, edges are (u - v),
                     meaning an edge from u to v also implies an edge from v to u.
        is_one_indexed: If True, node IDs in `edges` are assumed to be 1-indexed
                        and will be converted to 0-indexed internally for the
                        adjacency list keys and neighbor values. If False, node
                        IDs are assumed to be 0-indexed directly.

    Returns:
        A dictionary where keys are node IDs (0-indexed, from 0 to num_nodes-1)
        and values are sorted lists of their unique direct neighbors (also 0-indexed).
        All nodes from 0 to (num_nodes-1) will be present as keys, even if they have no edges.

    Raises:
        ValueError: If `num_nodes` is negative, or if any node ID in `edges` is
                    out of the valid range (0 to num_nodes-1 internally).

    # Sample Use Case 1: Undirected graph, 0-indexed input
    # num_nodes_1 = 4
    # edges_1 = [(0, 1), (1, 2), (2, 3), (3, 0), (0, 1)] # Duplicate edge (0,1) is handled
    # adj_list_1 = build_adjacency_list(num_nodes_1, edges_1)
    # print(adj_list_1)
    # # Expected: {0: [1, 3], 1: [0, 2], 2: [1, 3], 3: [0, 2]}

    # Sample Use Case 2: Directed graph, 1-indexed input
    # num_nodes_2 = 3
    # edges_2 = [(1, 2), (2, 3)] # Represents 1 -> 2, 2 -> 3
    # adj_list_2 = build_adjacency_list(num_nodes_2, edges_2, is_directed=True, is_one_indexed=True)
    # print(adj_list_2)
    # # Internally, 1-indexed nodes (1,2,3) map to 0-indexed (0,1,2).
    # # Edges (1,2) becomes (0,1). Edges (2,3) becomes (1,2).
    # # Expected: {0: [1], 1: [2], 2: []}

    # Sample Use Case 3: Graph with an isolated node
    # num_nodes_3 = 3
    # edges_3 = [(0, 1)]
    # adj_list_3 = build_adjacency_list(num_nodes_3, edges_3)
    # print(adj_list_3)
    # # Expected: {0: [1], 1: [0], 2: []}
    """
    if num_nodes < 0:
        raise ValueError("num_nodes cannot be negative.")

    # Initialize adjacency list using sets to automatically handle duplicate edges
    # and facilitate easy conversion to sorted lists later.
    adj_set: Dict[int, Set[int]] = {i: set() for i in range(num_nodes)}

    for u_raw, v_raw in edges:
        # Convert to 0-indexed if the input uses 1-indexed nodes
        u = u_raw - 1 if is_one_indexed else u_raw
        v = v_raw - 1 if is_one_indexed else v_raw

        # Validate node IDs to ensure they are within the expected 0 to num_nodes-1 range
        if not (0 <= u < num_nodes and 0 <= v < num_nodes):
            raise ValueError(
                f"Node ID pair ({u_raw}, {v_raw}) contains values out of range for "
                f"{num_nodes} nodes (valid internal 0-indexed range: 0 to {num_nodes-1})."
            )

        adj_set[u].add(v)
        if not is_directed:
            # For undirected graphs, add the reverse edge
            adj_set[v].add(u)

    # Convert sets of neighbors to sorted lists for consistent and readable output.
    final_adj_list: Dict[int, List[int]] = {
        node: sorted(list(neighbors)) for node, neighbors in adj_set.items()
    }

    return final_adj_list
