# Daily Utility Snippets - 2026-06-02
# Generated by Gemini 1.5 Flash based on daily topics

import math
from typing import Callable, List, TypeVar, Union

# Define a TypeVar for numerical types (int or float) to allow flexible type hinting.
Num = TypeVar('Num', int, float)

def sieve_of_eratosthenes(n: int) -> List[bool]:
    """
    Generates a boolean list indicating primality for numbers up to n using the Sieve of Eratosthenes algorithm.

    This function is efficient for finding all prime numbers up to a specified limit.
    It initializes all numbers from 2 to n as prime and then iteratively marks
    multiples of each prime as non-prime, starting from the square of the prime.
    Numbers 0 and 1 are explicitly marked as not prime.

    Args:
        n: The upper limit (inclusive) up to which primality is to be checked.
           Must be a non-negative integer.

    Returns:
        A list of booleans where `is_prime[i]` is True if `i` is a prime number,
        and False otherwise. The list is 0-indexed, so `is_prime[0]` and `is_prime[1]`
        will always be False. The length of the list is `n + 1`.

    Raises:
        ValueError: If n is negative.

    # Sample Use Case:
    # Generate primality array up to 100
    # primes_up_to_100 = sieve_of_eratosthenes(100)
    #
    # Check if a number is prime:
    # print(f"Is 2 a prime? {primes_up_to_100[2]}")  # Expected: True
    # print(f"Is 97 a prime? {primes_up_to_100[97]}") # Expected: True
    # print(f"Is 4 a prime? {primes_up_to_100[4]}")   # Expected: False
    # print(f"Is 101 a prime? (n=100, so 101 is out of bounds): N/A")
    #
    # Get a list of actual prime numbers up to 100:
    # list_of_primes = [i for i, is_p in enumerate(primes_up_to_100) if is_p]
    # print(f"Primes up to 100: {list_of_primes}")
    # # Expected: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
    """
    if n < 0:
        raise ValueError("n must be a non-negative integer.")
    if n < 2:
        return [False] * (n + 1)

    is_prime = [True] * (n + 1)
    is_prime[0] = is_prime[1] = False  # 0 and 1 are not prime numbers

    # Iterate up to sqrt(n). Multiples of primes greater than sqrt(n)
    # would have already been marked by smaller primes.
    p = 2
    while p * p <= n:
        # If is_prime[p] is still True, then it is a prime number.
        if is_prime[p]:
            # Mark all multiples of p (starting from p*p) as not prime.
            # Multiples less than p*p would have already been marked by smaller primes.
            for multiple in range(p * p, n + 1, p):
                is_prime[multiple] = False
        p += 1
    return is_prime


def binary_search_on_predicate(
    low: Num,
    high: Num,
    predicate: Callable[[Num], bool],
    target_smallest_true: bool = True,
    is_integer_range: bool = True,
    max_iterations: int = 100,
    epsilon: float = 1e-9
) -> Union[Num, None]:
    """
    Performs a binary search over a range [low, high] to find a specific value `x`
    that satisfies a given `predicate(x)`.

    This utility is extremely useful for "binary search on answer" problems, where
    you're searching for an optimal value (e.g., minimum, maximum) that satisfies
    a certain condition. The `predicate` function must exhibit monotonic behavior
    across the search range.

    Args:
        low: The inclusive lower bound of the search range.
        high: The inclusive upper bound of the search range.
        predicate: A callable that takes a value `x` (of type `Num`) and returns
                   a boolean. The `predicate` must be monotonic across the range.
                   Specifically:
                   - If `target_smallest_true` is True, we seek the smallest `x`
                     for which `predicate(x)` is True. This implies the sequence
                     `predicate(low)...predicate(high)` should look like
                     `False...False...True...True`.
                   - If `target_smallest_true` is False, we seek the largest `x`
                     for which `predicate(x)` is True. This implies the sequence
                     `predicate(low)...predicate(high)` should look like
                     `True...True...False...False`.
        target_smallest_true:
            - If True (default), the function finds the smallest `x` in `[low, high]`
              such that `predicate(x)` is True. (e.g., `F, F, T, T, T` -> finds first `T`)
            - If False, the function finds the largest `x` in `[low, high]`
              such that `predicate(x)` is True. (e.g., `T, T, T, F, F` -> finds last `T`)
        is_integer_range:
            - If True (default), the search operates on integers and returns an integer.
            - If False, the search operates on floats and returns a float.
        max_iterations: (Applicable for float ranges) Maximum number of iterations
                        to refine the float result. A typical value like 100-200
                        is usually sufficient for most precision requirements.
        epsilon: (Applicable for float ranges) The desired precision for the result.
                 For float searches, the loop can optionally terminate when `high - low`
                 is less than `epsilon`. However, fixed iterations are often preferred
                 in competitive programming to control runtime and avoid precision issues.

    Returns:
        The found value `x` (either int or float) that satisfies the criteria.
        Returns `None` if no such value is found in the given range.

    # Sample Use Case 1: Find the smallest integer whose square is at least 25 (e.g., finding sqrt ceiling)
    # predicate_sq_ge_25 = lambda x: x * x >= 25
    # result_1 = binary_search_on_predicate(0, 100, predicate_sq_ge_25, target_smallest_true=True, is_integer_range=True)
    # print(f"Smallest int x such that x*x >= 25: {result_1}") # Expected: 5
    #
    # Sample Use Case 2: Find the largest integer whose square is at most 25 (e.g., finding sqrt floor)
    # predicate_sq_le_25 = lambda x: x * x <= 25
    # result_2 = binary_search_on_predicate(0, 100, predicate_sq_le_25, target_smallest_true=False, is_integer_range=True)
    # print(f"Largest int x such that x*x <= 25: {result_2}") # Expected: 5
    #
    # Sample Use Case 3: Find the smallest float whose square is at least 2.0 (approx. sqrt(2))
    # predicate_sqrt_ge_2 = lambda x: x * x >= 2.0
    # result_3 = binary_search_on_predicate(0.0, 2.0, predicate_sqrt_ge_2, target_smallest_true=True, is_integer_range=False, max_iterations=100)
    # print(f"Smallest float x such that x*x >= 2.0: {result_3}") # Expected: ~1.41421356...
    #
    # Sample Use Case 4: Find the largest float `x` in [0, pi/2] for which `sin(x) < 0.5`. (x in radians)
    # predicate_sin_lt_0_5 = lambda x: math.sin(x) < 0.5
    # result_4 = binary_search_on_predicate(0.0, math.pi/2, predicate_sin_lt_0_5, target_smallest_true=False, is_integer_range=False, max_iterations=100)
    # print(f"Largest float x in [0, pi/2] such that sin(x) < 0.5: {result_4}") # Expected: ~0.52359877... (pi/6)
    """
    if low > high:
        return None

    if is_integer_range:
        current_low: int = int(low)
        current_high: int = int(high)
        ans: Union[int, None] = None  # Stores the best candidate found so far

        while current_low <= current_high:
            mid: int = current_low + (current_high - current_low) // 2
            if predicate(mid):
                if target_smallest_true:
                    ans = mid
                    current_high = mid - 1  # `mid` satisfies, try smaller values
                else:  # target_largest_true
                    ans = mid
                    current_low = mid + 1   # `mid` satisfies, try larger values
            else:  # predicate(mid) is False
                if target_smallest_true:
                    current_low = mid + 1   # `mid` is too small, need larger value
                else:  # target_largest_true
                    current_high = mid - 1  # `mid` is too large, need smaller value
        return ans
    else:  # Float range
        current_low_f: float = float(low)
        current_high_f: float = float(high)
        
        # Initial check for edge cases where no solution exists in the range.
        if target_smallest_true:
            # If we're looking for F...F T...T and predicate(high) is False, no T exists.
            if not predicate(current_high_f):
                return None
        else:  # target_largest_true
            # If we're looking for T...T F...F and predicate(low) is False, no T exists.
            if not predicate(current_low_f):
                return None

        # Fixed iteration count is generally safer for competitive programming
        # than `while high - low > epsilon` due to potential floating point inaccuracies.
        for _ in range(max_iterations):
            mid_f: float = current_low_f + (current_high_f - current_low_f) / 2.0
            
            # Optional: break early if the interval is already sufficiently small.
            if current_high_f - current_low_f < epsilon:
                break

            if predicate(mid_f):
                if target_smallest_true:
                    current_high_f = mid_f  # `mid` satisfies, potential answer, try smaller
                else:  # target_largest_true
                    current_low_f = mid_f   # `mid` satisfies, potential answer, try larger
            else:  # predicate(mid_f) is False
                if target_smallest_true:
                    current_low_f = mid_f   # `mid` is too small, need larger value
                else:  # target_largest_true
                    current_high_f = mid_f  # `mid` is too large, need smaller value
        
        # After iterations, `current_high_f` (for smallest_true) or `current_low_f` (for largest_true)
        # will hold the best approximation. A final predicate check ensures robustness.
        if target_smallest_true:
            return current_high_f if predicate(current_high_f) else None
        else:  # target_largest_true
            return current_low_f if predicate(current_low_f) else None
