# Daily Utility Snippets - 2026-07-07
# Generated by Gemini 1.5 Flash based on daily topics

import math
from typing import List, Tuple

def sieve_of_eratosthenes(limit: int) -> Tuple[List[bool], List[int]]:
    """
    Generates all prime numbers up to a given limit using the Sieve of Eratosthenes algorithm.

    This function precomputes primality for all numbers up to `limit` efficiently.
    It returns a boolean list `is_prime` where `is_prime[i]` is True if `i` is prime,
    and a list `primes` containing all prime numbers found within the limit.

    Args:
        limit: An integer representing the upper bound (inclusive) for prime generation.
               Must be non-negative.

    Returns:
        A tuple containing:
        - is_prime (List[bool]): A boolean list where `is_prime[i]` is True if `i` is prime, False otherwise.
                                 The list is of size `limit + 1`.
        - primes (List[int]): A sorted list of all prime numbers less than or equal to `limit`.

    Raises:
        ValueError: If limit is negative.

    Example:
        # Get primes up to 30
        is_prime_flags, prime_numbers = sieve_of_eratosthenes(30)
        # is_prime_flags would be [F, F, T, T, F, T, F, T, F, F, F, T, F, T, F, F, F, T, F, T, F, F, F, T, F, F, F, F, F, T, F]
        # is_prime_flags[7] would be True
        # prime_numbers would be [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

        # Check if 13 is prime
        # if 13 <= 30 and is_prime_flags[13]:
        #     print("13 is prime")
        # else:
        #     print("13 is not prime or outside limit")
    """
    if limit < 0:
        raise ValueError("Limit must be a non-negative integer.")
    if limit < 2:
        return [False] * (limit + 1), []

    is_prime = [True] * (limit + 1)
    is_prime[0] = is_prime[1] = False # 0 and 1 are not prime

    # Iterate from 2 up to sqrt(limit)
    for p in range(2, int(math.sqrt(limit)) + 1):
        if is_prime[p]:
            # Mark multiples of p (starting from p*p) as not prime
            for multiple in range(p * p, limit + 1, p):
                is_prime[multiple] = False

    primes = [p for p in range(limit + 1) if is_prime[p]]
    return is_prime, primes

def build_prefix_sum_array(arr: List[int]) -> List[int]:
    """
    Builds a 1D prefix sum array from the given input array.

    A prefix sum array (or cumulative sum array) `P` for an array `A`
    is an array where `P[i]` stores the sum of all elements from `A[0]` to `A[i-1]`.
    This allows for O(1) time complexity for range sum queries after an O(N) build time.

    The returned prefix sum array `P` will have `len(arr) + 1` elements.
    `P[0]` will be 0 (representing the sum of an empty prefix).
    `P[i]` (for `i > 0`) will be `arr[0] + arr[1] + ... + arr[i-1]`.

    Args:
        arr: The input list of integers. Can be empty.

    Returns:
        A list of integers representing the prefix sum array.

    Example:
        # Build prefix sum for an array
        my_array = [1, 2, 3, 4, 5]
        prefix_sums = build_prefix_sum_array(my_array)
        # prefix_sums would be [0, 1, 3, 6, 10, 15]

        # To query the sum of elements from index `start` (inclusive)
        # to `end` (exclusive) in the original array (i.e., arr[start] + ... + arr[end-1]):
        # The formula is: sum = prefix_sums[end] - prefix_sums[start]

        # Sum of my_array[0...2] (i.e., 1 + 2 + 3 = 6)
        # query_start = 0
        # query_end = 3 # sum up to index 2 (exclusive end)
        # range_sum_0_2 = prefix_sums[query_end] - prefix_sums[query_start]
        # print(range_sum_0_2) # Output: 6

        # Sum of my_array[2...4] (i.e., 3 + 4 + 5 = 12)
        # query_start = 2
        # query_end = 5 # sum up to index 4 (exclusive end)
        # range_sum_2_4 = prefix_sums[query_end] - prefix_sums[query_start]
        # print(range_sum_2_4) # Output: 12
    """
    n = len(arr)
    prefix_sum_arr = [0] * (n + 1)
    for i in range(n):
        prefix_sum_arr[i + 1] = prefix_sum_arr[i] + arr[i]
    return prefix_sum_arr
