# Daily Utility Snippets - 2026-06-03
# Generated by Gemini 1.5 Flash based on daily topics

import math
from typing import List, Callable, Union
from functools import lru_cache

@lru_cache(maxsize=None)
def sieve_of_eratosthenes(n: int) -> List[bool]:
    """
    Generates a boolean list indicating primality for numbers up to n using the Sieve of Eratosthenes.

    This function precomputes prime numbers up to a given limit 'n'.
    The result `is_prime[i]` will be True if 'i' is a prime number, and False otherwise.
    It handles n=0, 1 correctly (0 and 1 are not prime).

    Args:
        n: The upper limit (inclusive) up to which to find prime numbers.
           Must be a non-negative integer.

    Returns:
        A list of booleans `is_prime` where `is_prime[i]` is True if 'i' is prime,
        and False otherwise. The list has size `n + 1`.

    Raises:
        ValueError: If n is negative.

    # Example Usage 1: Check primality for numbers up to 10
    # is_prime_up_to_10 = sieve_of_eratosthenes(10)
    # # is_prime_up_to_10 will be [False, False, True, True, False, True, False, True, False, False, False]
    # print(f"Is 7 prime? {is_prime_up_to_10[7]}")  # Output: Is 7 prime? True
    # print(f"Is 6 prime? {is_prime_up_to_10[6]}")  # Output: Is 6 prime? False

    # Example Usage 2: Get a list of actual prime numbers up to 20
    # is_prime_array = sieve_of_eratosthenes(20)
    # primes_list = [i for i, status in enumerate(is_prime_array) if status]
    # print(f"Primes up to 20: {primes_list}")  # Output: Primes up to 20: [2, 3, 5, 7, 11, 13, 17, 19]

    # Example Usage 3: Handling edge cases
    # print(sieve_of_eratosthenes(0)) # Output: [False]
    # print(sieve_of_eratosthenes(1)) # Output: [False, False]
    """
    if n < 0:
        raise ValueError("n must be a non-negative integer.")

    is_prime = [True] * (n + 1)
    if n >= 0:
        is_prime[0] = False
    if n >= 1:
        is_prime[1] = False

    # Iterate from 2 up to sqrt(n). If a number 'p' is prime, mark all its multiples as not prime.
    # Multiples less than p*p would have already been marked by smaller prime factors.
    for p in range(2, int(math.sqrt(n)) + 1):
        if is_prime[p]:
            for multiple in range(p * p, n + 1, p):
                is_prime[multiple] = False
    return is_prime


def find_first_true_binary_search(
    low: Union[int, float],
    high: Union[int, float],
    predicate: Callable[[Union[int, float]], bool],
    is_int_search: bool = True,
    max_iterations: int = 100,
    epsilon: float = 1e-9
) -> Union[int, float, None]:
    """
    Performs a binary search to find the smallest value `x` (within [low, high])
    for which the `predicate(x)` is True.

    This utility is useful for "binary search on the answer" problems, where you're
    searching for a value `x` (not necessarily an index in an array) such that a
    given predicate function `P(x)` becomes true at `x` and remains true for
    all values greater than `x` (monotonicity). The function assumes a monotonically
    increasing predicate.

    Args:
        low: The lower bound of the search space (inclusive).
        high: The upper bound of the search space (inclusive).
        predicate: A callable function that takes a value (int or float) and returns a boolean.
                   It must be monotonically increasing, meaning if `predicate(x)` is True,
                   then `predicate(y)` must also be True for all `y > x`.
        is_int_search: If True, performs an integer binary search and returns an int.
                       If False, performs a float binary search and returns a float.
        max_iterations: For float searches, the maximum number of iterations to perform.
                        A sufficient number (e.g., 100-200) ensures good precision.
                        Ignored for integer searches.
        epsilon: For float searches, the desired precision. The search stops when
                 `high - low < epsilon`. Ignored for integer searches.

    Returns:
        The smallest `x` (int or float) in the range `[low, high]` for which
        `predicate(x)` is True. Returns `None` if `predicate(x)` is never true
        within the given range, or if `low > high`.

    Raises:
        ValueError: If `max_iterations` or `epsilon` are non-positive.

    # Example Usage 1: Integer search - find smallest number whose square is >= target
    # target = 25
    # def is_square_ge(num: int) -> bool:
    #     return num * num >= target
    # min_num = find_first_true_binary_search(0, target, is_square_ge, is_int_search=True)
    # print(f"Smallest integer whose square is >= {target}: {min_num}")  # Output: 5

    # Example Usage 2: Float search - find minimum x such that x cubed is >= 100
    # def is_cube_ge_100(val: float) -> bool:
    #     return val * val * val >= 100
    # min_val_float = find_first_true_binary_search(0.0, 10.0, is_cube_ge_100, is_int_search=False, max_iterations=100)
    # print(f"Smallest float whose cube is >= 100: {min_val_float:.6f}")  # Output: ~4.641589

    # Example Usage 3: Search space where predicate is never true
    # def always_false(num: int) -> bool:
    #     return False
    # no_result = find_first_true_binary_search(1, 10, always_false)
    # print(f"Result for always_false predicate: {no_result}")  # Output: None

    # Example Usage 4: Search space where predicate is always false initially
    # def is_ge_100(num: int) -> bool:
    #     return num >= 100
    # result_int_ge_100 = find_first_true_binary_search(1, 50, is_ge_100)
    # print(f"Smallest int >= 100 in [1, 50]: {result_int_ge_100}") # Output: None
