# Daily Utility Snippets - 2026-07-04
# Generated by Gemini 1.5 Flash based on daily topics

from typing import List, Optional, Deque
from collections import deque

class UnionFind:
    """
    A Disjoint Set Union (DSU) data structure for efficiently managing partitions of a set
    into a number of disjoint subsets. It supports two primary operations: finding
    the representative of a set (which can be used to check if two elements are
    in the same set) and uniting two sets.

    Optimized with path compression and union by rank.

    Topics: Union-Find, Graph Theory, Array, Tree (implicit structure).
    """
    def __init__(self, n: int):
        """
        Initializes the Union-Find structure with `n` elements, each in its own set.

        Args:
            n: The number of elements. Elements are 0-indexed (0 to n-1).
        """
        self.parent: List[int] = list(range(n))
        self.rank: List[int] = [0] * n  # Used for union by rank optimization
        self.num_sets: int = n

    def find(self, i: int) -> int:
        """
        Finds the representative (root) of the set containing element `i`.
        Applies path compression during the lookup for efficiency.

        Args:
            i: The element to find the set representative for.

        Returns:
            The representative (root) of the set containing `i`.
        """
        if self.parent[i] == i:
            return i
        # Path compression: make the current node's parent the root
        self.parent[i] = self.find(self.parent[i])
        return self.parent[i]

    def union(self, i: int, j: int) -> bool:
        """
        Unites the sets containing elements `i` and `j`.
        Uses union by rank to keep the tree flatter for efficiency.

        Args:
            i: The first element.
            j: The second element.

        Returns:
            True if the sets were different and were successfully united, False otherwise.
        """
        root_i = self.find(i)
        root_j = self.find(j)

        if root_i != root_j:
            # Union by rank: attach smaller rank tree under root of higher rank tree
            if self.rank[root_i] < self.rank[root_j]:
                self.parent[root_i] = root_j
            elif self.rank[root_j] < self.rank[root_i]:
                self.parent[root_j] = root_i
            else:
                self.parent[root_j] = root_i
                self.rank[root_i] += 1
            self.num_sets -= 1
            return True
        return False

    def get_num_sets(self) -> int:
        """
        Returns the current number of disjoint sets.
        """
        return self.num_sets

# Sample Use Case for UnionFind:
# uf = UnionFind(10) # 10 elements, 0 to 9
# uf.union(0, 1)
# uf.union(2, 3)
# uf.union(0, 2) # 0, 1, 2, 3 are now connected
# print(uf.find(1) == uf.find(3)) # Expected: True
# print(uf.get_num_sets()) # Expected: 7 (sets: {0,1,2,3}, {4}, {5}, {6}, {7}, {8}, {9})
# uf.union(4,5)
# print(uf.get_num_sets()) # Expected: 6


class TreeNode:
    """
    Definition for a binary tree node.
    Topics: Tree, Binary Tree, Binary Search Tree (can be used as base), Array (for list representation).
    """
    def __init__(self, val: int = 0, left: Optional['TreeNode'] = None, right: Optional['TreeNode'] = None):
        self.val = val
        self.left = left
        self.right = right

    def __repr__(self) -> str:
        # A simple representation for debugging purposes
        return f"TreeNode(val={self.val})"


def build_binary_tree_from_list(nodes: List[Optional[int]]) -> Optional[TreeNode]:
    """
    Builds a binary tree from a level-order list representation (e.g., LeetCode style).
    `None` values in the list indicate missing child nodes.

    Args:
        nodes: A list of integers or None, representing the tree in level order.
               For example, [3, 9, 20, None, None, 15, 7] represents:
                       3
                      / \
                     9  20
                       /  \
                      15   7

    Returns:
        The root TreeNode of the constructed binary tree, or None if the input list is empty
        or only contains None.

    Topics: Binary Tree, Tree, Array, Breadth-First Search (for construction).
    """
    if not nodes or nodes[0] is None:
        return None

    root_val = nodes[0]
    root = TreeNode(root_val)
    queue: Deque[TreeNode] = deque([root])
    i = 1

    while queue and i < len(nodes):
        current_node = queue.popleft()

        # Build left child
        if i < len(nodes) and nodes[i] is not None:
            left_child = TreeNode(nodes[i])
            current_node.left = left_child
            queue.append(left_child)
        i += 1

        # Build right child
        if i < len(nodes) and i < len(nodes) and nodes[i] is not None:
            right_child = TreeNode(nodes[i])
            current_node.right = right_child
            queue.append(right_child)
        i += 1
    return root

# Sample Use Case for build_binary_tree_from_list:
# nodes_list = [3, 9, 20, None, None, 15, 7]
# root = build_binary_tree_from_list(nodes_list)
# # To verify, you'd typically traverse it (e.g., level order traversal)
# # Example verification:
# # if root:
# #     print(root.val) # Expected: 3
# #     if root.left: print(root.left.val) # Expected: 9
# #     if root.right:
# #         print(root.right.val) # Expected: 20
# #         if root.right.left: print(root.right.left.val) # Expected: 15
# #         if root.right.right: print(root.right.right.val) # Expected: 7
#
# # Another example with an empty list
# empty_root = build_binary_tree_from_list([])
# # print(empty_root is None) # Expected: True
