# Daily Utility Snippets - 2026-07-03
# Generated by Gemini 1.5 Flash based on daily topics

from typing import List, Tuple

def sieve_of_eratosthenes(limit: int) -> List[bool]:
    """
    Generates a boolean list indicating primality for numbers up to 'limit'
    using the Sieve of Eratosthenes algorithm.

    This function is extremely useful for competitive programming and
    number theory problems requiring efficient prime number generation
    or primality testing for multiple numbers within a range.

    Args:
        limit: An integer representing the upper bound (inclusive)
               for prime generation. Must be non-negative.

    Returns:
        A list of booleans where `is_prime[i]` is True if `i` is a prime number,
        and False otherwise. The list is indexed from 0 to `limit`.

    Raises:
        ValueError: If `limit` is negative.

    Example:
        # Check primality up to 10
        is_prime_list = sieve_of_eratosthenes(10)
        # is_prime_list will be:
        # [False, False, True, True, False, True, False, True, False, False, False]
        # Primes are 2, 3, 5, 7

        assert not is_prime_list[0] # 0 is not prime
        assert not is_prime_list[1] # 1 is not prime
        assert is_prime_list[2]     # 2 is prime
        assert is_prime_list[7]     # 7 is prime
        assert not is_prime_list[9] # 9 is not prime

        # Find all primes up to 30
        primes_up_to_30 = [i for i, is_p in enumerate(sieve_of_eratosthenes(30)) if is_p]
        # primes_up_to_30 will be: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
    """
    if limit < 0:
        raise ValueError("Limit must be a non-negative integer.")
    if limit < 2:
        return [False] * (limit + 1)

    is_prime = [True] * (limit + 1)
    is_prime[0] = is_prime[1] = False  # 0 and 1 are not prime

    # Iterate up to sqrt(limit)
    p = 2
    while p * p <= limit:
        # If p is prime, mark all its multiples as not prime
        if is_prime[p]:
            for multiple in range(p * p, limit + 1, p):
                is_prime[multiple] = False
        p += 1

    return is_prime


def get_grid_neighbors(
    r: int,
    c: int,
    rows: int,
    cols: int,
    include_diagonals: bool = False
) -> List[Tuple[int, int]]:
    """
    Generates a list of valid neighboring cell coordinates for a given cell
    (r, c) within a 2D grid of specified dimensions.

    This utility is highly valuable in competitive programming and software
    engineering for problems involving grid traversal, simulations, pathfinding
    (BFS/DFS), and game development.

    Args:
        r: The row index of the current cell.
        c: The column index of the current cell.
        rows: The total number of rows in the grid.
        cols: The total number of columns in the grid.
        include_diagonals: If True, diagonal neighbors are included (8 directions).
                           If False (default), only cardinal neighbors are included
                           (4 directions: up, down, left, right).

    Returns:
        A list of tuples, where each tuple `(nr, nc)` represents the row and
        column indices of a valid neighbor cell. Neighbors that fall outside
        the grid boundaries are excluded.

    Raises:
        ValueError: If `rows` or `cols` are non-positive.

    Example:
        # 3x3 grid, cell (1,1)
        #   0 1 2
        # 0 . . .
        # 1 . X .
        # 2 . . .

        # Cardinal neighbors (4-directional)
        neighbors_4dir = get_grid_neighbors(1, 1, 3, 3)
        # neighbors_4dir will be: [(0, 1), (2, 1), (1, 0), (1, 2)] (order may vary)
        assert len(neighbors_4dir) == 4

        # Diagonal and cardinal neighbors (8-directional)
        neighbors_8dir = get_grid_neighbors(1, 1, 3, 3, include_diagonals=True)
        # neighbors_8dir will be:
        # [(0, 1), (2, 1), (1, 0), (1, 2), (0, 0), (0, 2), (2, 0), (2, 2)] (order may vary)
        assert len(neighbors_8dir) == 8

        # Edge case: cell (0,0) in a 2x2 grid, 4-directional
        #   0 1
        # 0 X .
        # 1 . .
        neighbors_corner = get_grid_neighbors(0, 0, 2, 2)
        # neighbors_corner will be: [(1, 0), (0, 1)] (order may vary)
        assert len(neighbors_corner) == 2

        # Edge case: cell (0,0) in a 1x1 grid, 8-directional (no neighbors)
        no_neighbors = get_grid_neighbors(0, 0, 1, 1, include_diagonals=True)
        assert len(no_neighbors) == 0
    """
    if rows <= 0 or cols <= 0:
        raise ValueError("Grid dimensions (rows, cols) must be positive integers.")

    # Delta arrays for 4-directional movement (up, down, left, right)
    dr_cardinal = [-1, 1, 0, 0]
    dc_cardinal = [0, 0, -1, 1]

    neighbors: List[Tuple[int, int]] = []

    # Add cardinal neighbors
    for i in range(4):
        nr, nc = r + dr_cardinal[i], c + dc_cardinal[i]
        if 0 <= nr < rows and 0 <= nc < cols:
            neighbors.append((nr, nc))

    # Add diagonal neighbors if requested
    if include_diagonals:
        # Delta arrays for diagonal movement (top-left, top-right, bottom-left, bottom-right)
        dr_diagonal = [-1, -1, 1, 1]
        dc_diagonal = [-1, 1, -1, 1]
        for i in range(4):
            nr, nc = r + dr_diagonal[i], c + dc_diagonal[i]
            if 0 <= nr < rows and 0 <= nc < cols:
                neighbors.append((nr, nc))

    return neighbors
